### ISSUE TITLE
broswer sample crash on scrolling website

### ISSUE THREAD

**Issue by 0x410c** [ultralight-ux/Ultralight#101]
**Summarize the Issue**
crash on scroll, also cant render any demo properly available on site

**Steps to Reproduce**
visit https://metroui.org.ua and scroll down on browser sample,

**Platform Info:**
 - OS: windows 10 1809
 - latest self compiled version

**Comment by adamjs** [comment]
Thanks for report, seems to involve an issue with allocator/recycler behavior in UltralightCore. I'll dive into this more and determine root cause.

**Comment by 0x410c** [comment]
thank you for at least acknowledging
