### ISSUE TITLE
CreateView throwing access 

### ISSUE THREAD

**Issue by TomerZeitune** [ultralight-ux/Ultralight#104]
Issue:
ultralight::Renderer::CreateView
throwing "Access violation executing location 0x00000000."
Code:

```
//running inside a cpp opengl application all events are working as their name suggests
class WebViewSystem : public System {
	ultralight::Ref<ultralight::Renderer> renderer_;
	ultralight::Ref<ultralight::View> view_;
	public:
	WebViewSystem(): 
	renderer_(ultralight::Renderer::Create()) ,
	view_(renderer_->CreateView(1000, 1000, false))//Thrown here
        {
		view_->LoadHTML("<h1>Hello!</h1><p>Welcome to Ultralight!</p>");
	}
	void Update() {
		renderer_->Update();
	}
	void Render()override {
		renderer_->Render();
		Texture frame(
			(unsigned char*)view_->bitmap()->raw_pixels()
			, view_->bitmap()->width()
			, view_->bitmap()->height()
			, view_->bitmap()->bpp());
		Events::scene->FindEntity("RenderTexture")->
			GetComponent<Material>()->texture = std::make_shared<Texture>(frame);
	}
};
```
The problem is that ultralight doesn't work becuase there is already an opengl context on the thread.
Maybe add the option to define something along the lines of 
`#define ULTRALIGHT_OPENGL_CONTEXT_ALREADY_SET
`
? 

**Platform Info:**
 - OS: Windows 10 
 - SDK Version 1.0.0 stable

**Comment by adamjs** [comment]
Should be fixed now, latest trunk no longer uses GL for rendering bitmaps offscreen-- now renders via pure-CPU to a lockable pixel buffer surface (see updated Tutorial 1).
