### ISSUE TITLE
Compiling and running tutorial 4 fails on macOS

### ISSUE THREAD

**Issue by BigJk** [ultralight-ux/Ultralight#108]
**Summarize the Issue**
I try to compile the Tutorial 4 without success. The problem is caused by the following line
```C++
global["GetMessage"] = BindJSCallback(&MyApp::GetMessage);
```

Compiling yields:
```
Undefined symbols for architecture x86_64:
  "ultralight::JSPropertyValue::operator=(std::function<void (ultralight::JSObject const&, std::vector<ultralight::JSValue, std::allocator<ultralight::JSValue> > const&)> const&)", referenced from:
      MyApp::OnDOMReady(ultralight::View*)        in main.cpp.o
  "ultralight::Overlay::Create(ultralight::Ref<ultralight::Window>, int, int, int, int)", referenced from:
      MyApp::MyApp(ultralight::Ref<ultralight::Window>) in main.cpp.o
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
```

**Steps to Reproduce**
Compile and run the Tutorial 4 von macOS

**Platform Info:**
 - OS: macOS
 - SDK Version: 1.0
- gcc: 8.2.0
- cmake: 3.13.4

**Comment by raff** [comment]
This does work with the standard MacOS C++ compiler:

    $ gcc --version
    Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX .   10.14.sdk/usr/include/c++/4.2.1
    Apple LLVM version 10.0.1 (clang-1001.0.46.4)
    Target: x86_64-apple-darwin18.6.0
    Thread model: posix
    InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
