### ISSUE TITLE
BindJSCallback not working

### ISSUE THREAD

**Issue by brunph** [ultralight-ux/Ultralight#111]
if i try and bind js call back, vs studio tells me " 'this' may only be used inside a nonstatic member function", how would i solve this?

**Comment by tim37021** [comment]
I am not sure if it take std::function as argument but you can try std::bind

**Comment by brunph** [comment]
yeah well i got it to work, only problem is that the arguments doesn't have any good documentation, so i can't find how to receive arguments from javascript to c++.

**Comment by adamjs** [comment]
Sample 4 demonstrates how to use the JSHelpers API in the latest release (1.3.0): 

<https://github.com/ultralight-ux/Samples/blob/master/Sample%204%20-%20JavaScript/main.cpp>
