### ISSUE TITLE
Unity integration 

### ISSUE THREAD

**Issue by TopGameStudios** [ultralight-ux/Ultralight#112]
Can we use it in unity, to render websites using their URL?

**Comment by TomerZeitune** [comment]
Technically you should be able to do that. I suggest creating a Unity Native plug-in of Ultralight HTML and creating a GPU driver implemention with Unity's Command Buffer or with he Unity GL class. It’s possible but not easy.

**Comment by TopGameStudios** [comment]
Ohk
