### ISSUE TITLE
Can't find the reference FileSystem platform implementations in SDK

### ISSUE THREAD

**Issue by infamicstudios** [ultralight-ux/Ultralight#113]
In the Wiki documentation (https://github.com/ultralight-ux/Ultralight/wiki/Platform-Handlers) it states that 

> Reference implementations for Windows and macOS, as well as a basic FileSystem loader that uses the C++ STL (FileSystemBasic) is provided in the Framework code (see deps/Framework/platform/ in the SDK).

However, in the SDK downloaded from https://ultralig.ht/ this directory is entirely missing. Maybe I am not looking in the right place or at the right thing?

**Comment by adamjs** [comment]
The SDK and repo structure is currently being restructured-- all platform implementations and driver code is now part of AppCore, see: https://github.com/ultralight-ux/AppCore 

I'll update the docs accordingly.
