### ISSUE TITLE
Static Library for single 

### ISSUE THREAD

**Issue by NothingFaceX** [ultralight-ux/Ultralight#114]
Hi , Any chance to release a static library ?
I know a method to do it manually with converting dll to a static asm codes and load it from run time from memory but it would be great if Ultralight comes with static library itself.
Thanks.

**Comment by adamjs** [comment]
Unfortunately there’s a bit of a licensing issue— the WebCore module contains LGPL code and must be linked dynamically to maintain a clear separation between LGPL and proprietary components.
