### ISSUE TITLE
api-ms-win-shcore-scaling-l1-1-1 is missing

### ISSUE THREAD

**Issue by IWreck** [ultralight-ux/Ultralight#117]
Windows 7 - Affects all demo project except "Test 1"

**Comment by adamjs** [comment]
This issue should be fixed in latest repo, see the previous thread: https://github.com/ultralight-ux/Ultralight/issues/50

I'll be publishing v1.1 soon with the changes.

**Comment by IWreck** [comment]
Ok sorry, I looked at post date and thought the problem had returned.
