### ISSUE TITLE
Expose a C function to get a char* or ULChar8* from ULString

### ISSUE THREAD

**Issue by raff** [ultralight-ux/Ultralight#122]
Currently the only way to get the content of ULString in C is via "ulStringGetData(ULString str)". For binding to other languages it would be more convenient to have another method that returns ULChar8* (utf-8) or char*

**Comment by adamjs** [comment]
I agree, this would be a worthy addition. I’ll add.

**Comment by adamjs** [comment]
`ulStringGetData()` now returns a null-terminated UTF-8 C-String in the latest release (1.3.0). This function previously returned a UTF-16 buffer but the internal representation for Strings have been switched over to UTF-8.

See the C API for details: https://ultralig.ht/api/c/1_3_0/_c_a_p_i___string_8h.html
