### ISSUE TITLE
Cannot link on linux

### ISSUE THREAD

**Issue by raff** [ultralight-ux/Ultralight#123]
When trying to compile one of the test programs in Linux I get the following missing symbol (both when buiding with cmake and directly via c++):

     > c++ -o test -I../../build/SDK/include -L../../build/SDK/bin main.cpp -lUltralight -lUltralightCore -lWebCore

    ../../build/SDK/bin/libUltralightCore.so: undefined reference to `ultralight::CreatePlatformFontLoader()'
    collect2: error: ld returned 1 exit status

**Comment by adamjs** [comment]
Oops, haven’t implemented a default platform font loader in the latest UltralightCore module on Linux yet. I’ll fix.

**Comment by adamjs** [comment]
This is fixed now in trunk.
