### ISSUE TITLE
Crash in JavaScriptCore on Windows

### ISSUE THREAD

**Issue by adamjs** [ultralight-ux/Ultralight#130]
Crash while running JetStream: https://browserbench.org/JetStream1.1

Only reproducible in optimized build on Windows.

Seems to be crash involving garbage collected JSValue on worker thread. Might be related to fact we aren’t using JavaSciptCore’s default allocator (bmalloc). Will revisit after adding bmalloc.

**Comment by catid** [comment]
Also crashes in latest debug build for me

**Comment by adamjs** [comment]
This is resolved in latest 1.2 branch.
