### ISSUE TITLE
GPUDriverGL Does not work with GLFW.

### ISSUE THREAD

**Issue by TomerZeitune** [ultralight-ux/Ultralight#136]
Hello, I asked about this on Slack. And there seems to be a problem either with my code or with the GL driver code. 

I am trying to render the view to the screen using render_target().texture_id. No texture is being displayed. 

Here's my code:
```

#include <OpenGL/GPUDriverGL.h>//AppCore's GL Driver
#include <Ultralight/Ultralight.h>
#include <AppCore/AppCore.h>
#include <GLFW/glfw3.h>

using namespace ultralight;

int main() {
	GLFWwindow* window;
	
	if (!glfwInit())
		return -1;

	window = glfwCreateWindow(600, 600, "View", NULL, NULL);

	if (!window)
	{
		glfwTerminate();
		return -1;
	}
	
	glfwMakeContextCurrent(window);
	glewInit();
	glEnable(GL_TEXTURE_2D);
	Config config;
	config.face_winding = kFaceWinding_CounterClockwise; // CW in D3D, CCW in OGL
	config.device_scale_hint = 1.0;               // Set DPI to monitor DPI scale
	config.font_family_standard = "Segoe UI";     // Default font family
	GPUDriver* driver = new GPUDriverGL(1);
	Platform& platform = Platform::instance();
	platform.set_config(config);
	platform.set_gpu_driver(driver);
	
	auto UIRenderer = Renderer::Create();
	auto UIView = UIRenderer->CreateView(600, 600, true);
	UIView->LoadHTML("<h1>test</h1>");
	glClearColor(0, 0, 1, 1);
	
	while (!glfwWindowShouldClose(window))
	{	
		glClear(GL_COLOR_BUFFER_BIT);
		UIRenderer->Update();
		
		UIRenderer->Render();
		
		if (driver->HasCommandsPending()) {
			driver->DrawCommandList();
			driver->BindTexture(0,UIView->render_target().texture_id);
			glBegin(GL_QUADS);
			glTexCoord2f(0.0, 1.0);
			glVertex3f(-1.0f, -1.0f, 0.0f);
			glTexCoord2f(0.0, 0.0);
			glVertex3f(-1.0f, 1.0f, 0.0f);
			glTexCoord2f(1.0, 0.0);
			glVertex3f(1.0f, 1.0f, 0.0f);
			glTexCoord2f(1.0, 1.0);
			glVertex3f(1.0f, -1.0f, 0.0f);
			glEnd();
			glfwSwapBuffers(window);	
		}
		glfwPollEvents();
	}
	glfwTerminate();
	return 0;
}


```
I see the clear color only (blue). 

Is there anything wrong on my side ?

**Comment by IanByun** [comment]
short answer:
ultralight::Renderer creates its own GL context, which collides with other GL, GLUT, GLFW windows creation.
If one could *share* ultralight::Renderer implementation, we could find the source of the problem and possibly solution.

**Comment by IanByun** [comment]
I confirmed that,
If glut is used and Renderer  is run on another thread, it is ok.
But glfw, I have no clue.
Any one with ideas?

**Comment by IanByun** [comment]
@TomerZeitune I see that you opened a related issue https://github.com/ultralight-ux/Ultralight/issues/104.
Any progress with conflicting opengl contexts?

**Comment by TomerZeitune** [comment]
@IanByun This time I actually went to the OpenGL Driver’s code and removed the line creating a new OpenGL context , now it’s just using the context I already have on the thread. I don’t think this current issue is related to the other issue with the conflicting contexts.

**Comment by IanByun** [comment]
@TomerZeitune Thanks for the advice. I'll look into it.

**Comment by IanByun** [comment]
@TomerZeitune Thanks to you, I completely ditched GPUContextGL, and digged into GPUDriverGL.
I use openframeworks, so I really dont know all the details regarding how opengl actually works.
I managed to read pixel data of a webpage back to CPU memory, and imshow using opencv.

If it helps, here is how I did it.
I guess is that there is missing part of assigning rbuf_texture_id to render_target().texture_id.

When GPUDriverGL creates a render buffer, manually save rbuf_texture_id that is attached to the frame_buffer_id.
https://github.com/ultralight-ux/AppCore/blob/master/src/linux/gl/GPUDriverGL.cpp#L210

Then read back texture data to cpu pixels (960 is width, 540 is height, 4 is for rgba).
Here, tex_id is rbuf_texture_id.
```
std::vector<uchar> frame_data(960 * 540 * 4);
glBindTexture(GL_TEXTURE_2D, tex_id);
glGetTexImage(GL_TEXTURE_2D, 0, GL_RGBA, GL_UNSIGNED_BYTE, &frame_data[0]);
```

check the results with imshow
```
cv::Mat bmat = cv::Mat(540, 960, CV_8UC4, frame_data.data());
cv::cvtColor(bmat, bmat, cv::COLOR_RGBA2BGR);
cv::imshow("ast.mat", bmat);
cv::waitKey(1);
```
![image](https://user-images.githubusercontent.com/6938192/62993912-60347a80-be94-11e9-9b6c-9e94a33ddcd4.png)

**Comment by IanByun** [comment]
@TomerZeitune I think I figured it out.

What **RenderTarget View::render_target()** holds as texture_id is
merely a key for a map of opengl texture ids, **map<int, GLuint> GPUDriverGL::texture_map**,
which was the meaning of
> The GPUDriver-specific texture ID (you should bind the texture using
> your implementation of GPUDriver::BindTexture before drawing a quad).

In short, 
`glBindTexture(GL_TEXTURE_2D, texture_map[render_target.texture_id]);
`

**Comment by TomerZeitune** [comment]
Very interesting. So how would you go about obtaining the id of the actual opengl texture ?

**Comment by IanByun** [comment]
> @IanByun Very interesting. So how would you go about obtaining the id of the actual opengl texture ?

I mistakenly deleted my previous response...

My snippet is like this, basically `GPUDriverGL::texture_map[render_target.texture_id]`
```
void ReadTextureToPBO(GLuint tex_id, GLuint pbo_id, OUT const std::vector<BYTE>& pixel_data) {
    glBindBuffer(GL_PIXEL_PACK_BUFFER, pbo_id);
    glBindTexture(GL_TEXTURE_2D, tex_id);
    glGetTexImage(GL_TEXTURE_2D, 0, GL_RGBA, GL_UNSIGNED_BYTE,
        (GLvoid*)0 // offset in bytes into "buffer", not pointer to client memory!
    );
    glBufferData(GL_PIXEL_PACK_BUFFER, pixel_data.size(), 0, GL_STREAM_READ); 

    GLubyte* dma_ptr = (GLubyte*)glMapBuffer(GL_PIXEL_PACK_BUFFER, GL_READ_ONLY);
    if (dma_ptr) { 	// update data directly on the mapped buffer
        memcpy((void*)pixel_data.data(), dma_ptr, 960 * 540 * 4);
        glUnmapBuffer(GL_PIXEL_PACK_BUFFER); // release the mapped buffer
    }
    glBindTexture(GL_TEXTURE_2D, 0);
    glBindBuffer(GL_PIXEL_PACK_BUFFER, 0);
}

void CopyTextureFromFBO(GLuint fbo_id, OUT const ofTexture& tex) {
    int tex_id = tex.texData.textureID;
    int tex_target = tex.texData.textureTarget;
    int tex_format = tex.texData.glInternalFormat;
    GL_RGB8;
    glBindFramebuffer(GL_FRAMEBUFFER, fbo_id);
    glBindTexture(tex_target, tex_id);
    //glCopyTexImage2D(tex_target, 0, tex_format, 0, 0, width, height, 0);
    glCopyTexSubImage2D(tex_target, 0, 0, 0, 0, 0, width, height);
    glBindTexture(tex_target, 0);
    glBindFramebuffer(GL_FRAMEBUFFER, 0);
}

auto web_assets = web_loader->getViewAssets();
auto driver = static_cast<GPUDriverGL*>(web_loader->gpu_driver);

auto frame_map = driver->GetFrameMap();
auto texture_map = driver->GetTextureMap();

if (frame_map.size() != 0) {
    auto render_target = web_assets[3].view->render_target();
    GLint fbo_id = frame_map[render_target.render_buffer_id];
    GLint tex_id = texture_map[render_target.texture_id];

    ReadTextureToPBO(tex_id, pbo_id, frame_data);

    CopyTextureFromFBO(fbo_id, of_tex);
    of_tex.draw(0, 0, 960, 540);

    cv::Mat bmat = cv::Mat(540, 960, CV_8UC4, (void*)frame_data.data());
    cv::cvtColor(bmat, bmat, cv::COLOR_RGBA2BGR);

    cv::imshow("ast.mat", bmat);
    cv::waitKey(1);
}
```

**Comment by TomerZeitune** [comment]
Did you modify GPUDriverGL in any way?

**Comment by IanByun** [comment]
Only some getters to retrive std::map objects.

**Comment by TomerZeitune** [comment]
In my snippet of code I'm already user GPUDriverGL::BindTexture so why is it still not working? Am I missing something on my side?

**Comment by IanByun** [comment]
Hmm. My guess is two fold.

First is, maybe the driver already drew all the stuff, so no commnads are pending.

Second is, have you checked glError?
I received invalid opertions for glBegin(GL_QUADS), and google search results say that recent opengl do not allow glBegin.

**Comment by adamjs** [comment]
For easier integration into GL and other GPU environments, the library now supports rendering offscreen to a lockable pixel buffer surface using a pure-CPU, SIMD-accelerated architecture (see Config::use_gpu_renderer and the new Surface API in trunk). Tutorial 1 in latest trunk demonstrates how to render to an offscreen bitmap surface using this API.
