### ISSUE TITLE
High GPU usages on Window10

### ISSUE THREAD

**Issue by wxjz2** [ultralight-ux/Ultralight#137]
tested a scrolling text js using  jquery.marquee compents,   gpu usage more than 40% on Intel HD  4600  notebook,  using firefox/chrome/ie/edge GPU usage only 5%. full sample code in attached file.
[TitleWeb.zip](https://github.com/ultralight-ux/Ultralight/files/3323203/TitleWeb.zip)

**Comment by adamjs** [comment]
Should be lower now-- also you can now enable the CPU renderer for platforms with limited GPU hardware.
