### ISSUE TITLE
Can't link on Ubuntu 16.04

### ISSUE THREAD

**Issue by ddv2005** [ultralight-ux/Ultralight#139]
Hello,

Compiling on Ubuntu 16.04 give me an error:
/root/Ultralight/build/SDK/bin/libUltralightCore.so: undefined reference to `std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)())@GLIBCXX_3.4.22'
/root/Ultralight/build/SDK/bin/libUltralightCore.so: undefined reference to `std::thread::_State::~_State()@GLIBCXX_3.4.22'

**Comment by adamjs** [comment]
Make sure to use Clang when compiling the library, all bins in the latest release (1.3.0) for Linux are built against Ubuntu 18.04 / Clang.
