### ISSUE TITLE
Browser Sample Crashs on Win10 8 and 7 & Full Screen Problem And ....!

### ISSUE THREAD

**Issue by NothingFaceX** [ultralight-ux/Ultralight#141]
Hi Adam 
I'm using visual studio 2013 ultimate , Windows 7 x64 ultimate & Win SDK 7.1A to build browser sample , build success with no error but when I launch the app it will crash on start up after window appears.

**Here's browser sample build :**
http://s000.tinyupload.com/index.php?file_id=58807183198941244959

Also it goes wrong on full screen mode :
http://uupload.ir/files/mwvk_full_screen.jpg

Can it be because I use windows 7 SDK ?

**Comment by NothingFaceX** [comment]
Also I tried build on windows 7 8 10 and all crash.

**Comment by uspasojevic96** [comment]
Do you have any crash log?

**Comment by NothingFaceX** [comment]
how can I get log ?
i can send debug symbols

**Comment by adamjs** [comment]
Can you try rebuilding with latest debug SDK for Windows/x86? Download it here: https://ultralight-sdk-dbg.sfo2.cdn.digitaloceanspaces.com/ultralight-sdk-latest-win-x86.7z

Stepping into a debugger, it shows a crash somewhere in AppCore but we need debug symbols to pinpoint where.

This is probably related to a previous issue we resolved-- AppCore was built with VS2015 and a previous build used `std::vector` in the JSHelpers header which created a dependency on the STL headers of VS2015. (Latest trunk shouldn't have this issue anymore)

**Comment by NothingFaceX** [comment]
Hi Dear @adamjs , I'm testing it , Also I installed all of directx11 run times on my windows 7
but it always shows 'Failed to initialize D3D11 context' error in windows 7.

**Comment by adamjs** [comment]
What's your machine spec / video card?

**Comment by NothingFaceX** [comment]
Desktop - Inter i7-4770 8 Thread - Ram 12GB - Graphic Card : NVIDIA Geforce GTX 660 Ti 2015MB
Windows 10 Latest Build - Windows 7 Ultimate
