### ISSUE TITLE
Wrong description of Ref<App> Create()

### ISSUE THREAD

**Issue by IanByun** [ultralight-ux/Ultralight#147]
This is copy of https://github.com/ultralight-ux/AppCore/issues/2.

 Ref<App> Create() comments say that one should "set your Config before creating App".
https://github.com/ultralight-ux/AppCore/blob/0dfc7936e4ecdce4655b52dfb682ec40c080eb63/include/AppCore/App.h#L51

However, as AppWin::AppWin() constructor overrides with Platform::instance().set_config, it has no effect.
https://github.com/ultralight-ux/AppCore/blob/0dfc7936e4ecdce4655b52dfb682ec40c080eb63/src/win/AppWin.cpp#L23

For example, if I load https://google.co.kr like below,
```
auto& platform = ultralight::Platform::instance();

Config config;
config.font_family_standard = "Malgun Gothic";
config.font_family_fixed = "Malgun Gothic";
config.font_family_serif = "Malgun Gothic";
config.font_family_sans_serif = "Malgun Gothic";
config.user_agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36";

platform.set_config(config);

app_ = App::Create();
```

The result is like this:
![image](https://user-images.githubusercontent.com/6938192/62864268-32d9b680-bd46-11e9-87ea-984e43cc5b10.png)

The ***CORRECT*** way to setup config is,
```
app_ = App::Create();

auto& platform = ultralight::Platform::instance();

Config config;
config.font_family_standard = "Malgun Gothic";
config.font_family_fixed = "Malgun Gothic";
config.font_family_serif = "Malgun Gothic";
config.font_family_sans_serif = "Malgun Gothic";
config.user_agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36";

platform.set_config(config);

app_->renderer() = Renderer::Create(); //this overides default config with 'my' config
```

which leads to Chrome-like correctly rendered scene.
![image](https://user-images.githubusercontent.com/6938192/62864382-8b10b880-bd46-11e9-8538-f94fd2a0fbc3.png)

**Comment by adamjs** [comment]
This is fixed in the latest version (1.1), `App::Create()` now allows you to pass Config and Settings directly.

```  ///
  /// Create the App singleton.
  ///
  /// @param  settings  Settings to customize App runtime behavior.
  ///
  /// @param  config  Config options for the Ultralight renderer.
  ///
  /// @return  Returns a ref-pointer to the created App instance.
  ///
  /// @note  You should only create one of these per application lifetime.
  ///
  /// @note  Certain Config options may be overridden during App creation,
  ///        most commonly Config::face_winding and Config::device_scale_hint.
  ///
  static Ref<App> Create(Settings settings = Settings(), Config config = Config());
```
