### ISSUE TITLE
Expose C API for easier bindings generation.

### ISSUE THREAD

**Issue by adamjs** [ultralight-ux/ultralight#15]

**Comment by spikespaz** [comment]
LMK in this thread when this is finished. Thanks!

**Comment by adamjs** [comment]
This is now available in v1.0.

**Comment by bravepuzzle** [comment]
Any chance you could link the commits related for reference?

**Comment by adamjs** [comment]
The C API is exposed via the CAPI.h headers in Ultralight and AppCore includes.

Ultralight C API:
https://github.com/ultralight-ux/ultralight/blob/master/include/Ultralight/CAPI.h

AppCore C API:
https://github.com/ultralight-ux/ultralight/blob/master/include/AppCore/CAPI.h

JavaScriptCore is already written in C:
https://github.com/ultralight-ux/ultralight/tree/master/include/JavaScriptCore

**Comment by bravepuzzle** [comment]
Thank you very much!
