### ISSUE TITLE
[macOS] Browser Sample can't receive paste content from clipboard (cmd+C, cmd+V) and Can't use the input method.

### ISSUE THREAD

**Issue by tommyZZM** [ultralight-ux/Ultralight#152]
OS: macOS 10.14.6
sample: Browser Sample

1) Can't receive paste content from clipboard (cmd+C, cmd+V)
2) Can't use the input method. (input chinese words to the input element)

Can these features implementable in the sample?

**Comment by ecssolutions** [comment]
I have the same issue. Also selecting text inside the input box is not possible by mouse. Selecting text with shortcuts works on macOS by using CTRL+A instead of CMD+A. Weirdly enough both CTRL+C/V and CMD+C/V does not work.

**Comment by radq85** [comment]
Did anyone found out how to enable copy/paste feature? I am facing the same problem as above. 
I am running macOS 10.14.6

**Comment by adamjs** [comment]
Cut/copy/paste and text selection is now available in current trunk, Input Method Editor integration is in progress here (please follow it to receive updates): https://github.com/ultralight-ux/Ultralight/issues/24
