### ISSUE TITLE
Intercept object destruction from C code

### ISSUE THREAD

**Issue by APerricone** [ultralight-ux/Ultralight#155]
Hello, 
I am using ultralight from C code, now I have the necessity to intercept where the ULWindow is destroyed.
On C++ it is simple, derive the class and overload the destructor, but in C code it is necessary add a callback for this purpose...
Any ideas?

**Comment by adamjs** [comment]
You can use `ulWindowSetCloseCallback()` for this purpose, from the C API:

```
typedef void (*ULCloseCallback) (void* user_data);

///
/// Set a callback to be notified when a window closes.
///
ACExport void ulWindowSetCloseCallback(ULWindow window,
                                       ULCloseCallback callback,
                                       void* user_data);
```
