### ISSUE TITLE
Minimum ram and "rom"

### ISSUE THREAD

**Issue by baldhead69** [ultralight-ux/Ultralight#158]
Hi,

What the minimum ram and "rom" memory, and minimum processor features to run ultralight ?

Thank's.

**Comment by baldhead69** [comment]
???????????????????????????????

**Comment by niutech** [comment]
The basic app (sample 2) of Ultralight 1.2 for Windows 10 64-bit uses 48MB of RAM and 72MB of HDD, the sample browser uses 68MB of RAM and 81MB of HDD.

**Comment by baldhead69** [comment]
So forget to use ultralight in a resources limited embedded world. 😁

Thank's.

**Comment by uspasojevic96** [comment]
I personally use LVGL for embedded UI until UL gets full support

**Comment by baldhead69** [comment]
I am using lvgl now.

**Comment by niutech** [comment]
If you need a really lightweight, although very basic web engine, try: Nesurf, Dillo or Links in graphics mode. But for making embedded GUI there are much better tools, like Nuklear or Dear ImGui.
