### ISSUE TITLE
Enable WebAssembly

### ISSUE THREAD

**Issue by Rjvs** [ultralight-ux/Ultralight#168]
This is just a tracking issue, as I understand that the ability to run WebAssembly binaries should come 'for free' when Adam next integrates upstream WebKit.

**Comment by adamjs** [comment]
Just a note on this-- WebAssembly depends on enabling the FTL/B3 JIT in JavaScriptCore which is no longer supported on x86 32-bit platforms (Apple seems to be deprecating this platform). When I do enable this feature it will likely only be available on 64-bit platforms.

**Comment by gdeverlant** [comment]
Apple should die slowly!

**Comment by adamjs** [comment]
WebAssembly is now enabled by default in the 1.2 branch.
