### ISSUE TITLE
Add support for WebSockets over SSL

### ISSUE THREAD

**Issue by adamjs** [ultralight-ux/Ultralight#171]
Our branch of WebCore (specifically, cURL requests) doesn't support WebSockets over SSL-- upstream trunk has the fix, just need to pull and merge.

**Comment by adamjs** [comment]
This is now working in latest 1.2 branch.

**Comment by WebDevM4DC** [comment]
Unfortunately, I just tested this using Sample 8 and it does not work. Websockets over SSL do not work.

Any suggestions ? :(

![Screenshot_9](https://user-images.githubusercontent.com/78352751/113147489-bc464100-9228-11eb-8f33-7d34f47590f5.png)

**Comment by WebDevM4DC** [comment]
This is a websocket request on Chrome:

```
Accept-Encoding: gzip, deflate, br
Accept-Language: en-GB,en-US;q=0.9,en;q=0.8
Cache-Control: no-cache
Connection: Upgrade
Host: wss.ca1.broadcastcentre.com
Origin: https://broadcastcentre.com
Pragma: no-cache
Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits
Sec-WebSocket-Key: JJFMPsLQK9uaNP/svt5CBQ==
Sec-WebSocket-Version: 13
Upgrade: websocket
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36
```

As you can see it's just missing Upgrade: websocket, if you can add that... problem solved.
