### ISSUE TITLE
new  WebCore cannot run  

### ISSUE THREAD

**Issue by zhouzusheng** [ultralight-ux/Ultralight#174]
i build   WebCore.dll from  ultralight-ux/WebCore's master branch. but when i replace   the Ultralight SDK's Webcore.dll with the new one,  the sample app such as Browser cannot launch. 
it seem that  the interfaces ( both Ultralight and WebCore  ) are changed.
How to run with the new WebCore.dll?

**Comment by adamjs** [comment]
The interfaces between the WebCore module and Ultralight/UltralightCore modules has changed-- I'm releasing an update for 1.1 shortly that will update and synchronize all the modules into one package. I'll update this ticket once it's up.

**Comment by adamjs** [comment]
The new modules are now live on master branch of this repo (see Deps.cmake, just re-run the cmake build scripts to pull the new deps).
