### ISSUE TITLE
Document requirements to build/run samples

### ISSUE THREAD

**Issue by Ivshti** [ultralight-ux/ultralight#18]
**Is your feature request related to a problem? Please describe.**
Once you download the SDK for Windows and try to build and run, there are a few things required that are not explicitly mentioned.

**Describe the solution you'd like**
Make a guide that explains clearly how to setup your environment in order to build and run the samples

This basically includes two things

- obviously, visual studio (community edition 2017)
- more importantly, d3d11 debug layer: https://stackoverflow.com/questions/32809169/use-d3d11-debug-layer-with-vs2013-on-windows-10/32828880

**Comment by adamjs** [comment]
Thanks! I'll make sure to update the documentation, good to know about D3D11 Debug Layer.
