### ISSUE TITLE
Rendering issues with fractional DPI scaling

### ISSUE THREAD

**Issue by adamjs** [ultralight-ux/Ultralight#186]
Using fractional DPI (eg, 1.25 or 1.75) occasionally causes blurring artifacts if render textures are not a multiple of these because we rely on having a 1:1 texel/pixel mapping when doing font rendering and compositing layers. 

Fix this by padding render textures to a multiple of the fractional DPI so that when we scale the viewport we still have a 1:1 texel mapping.

**Comment by sirgru** [comment]
After building examples and trying on Windows 8.1 with 1.25 scaling, the resizable example gets more and more blurry the more it is resized. 
![Blurry](https://i.ibb.co/K21K9ts/Blurry.png)
There also seems to be some kind of vertical black line on the right side of the window after resizing.
![Blurry](https://i.ibb.co/0yHqRTD/Line.png)

**Comment by adamjs** [comment]
This is fixed in latest trunk, (most of the worst-offending glyph scaling issues at least, may need more work to make sure all geometry is pixel snapped).
