### ISSUE TITLE
Error when running Tutorial 1 Windows

### ISSUE THREAD

**Issue by sirgru** [ultralight-ux/Ultralight#193]
After running Tutorial 1 - Render to PNG, there is this error in the console:
`Error: WGL: Failed to clear current context: The handle is invalid.`

There is a .png image generated and it does have text rendered.

This is on Windows 7 and 8.1.

**Comment by Mizumaky** [comment]
Have the same problem on latest Windows 10

**Comment by adamjs** [comment]
This should be fixed-- offscreen renderer no longer uses GL (now renders via pure-CPU SIMD architecture). Try latest Tutorial 1 in trunk.
