### ISSUE TITLE
ulSettingsSetFileSystemPath doesn't create implicit root

### ISSUE THREAD

**Issue by Rjvs** [ultralight-ux/Ultralight#196]
Attempting to load and display an HTML file in `a:\foo\bar.html` using CAPI, I was expecting to be able to create an implicit root path that isolates the rest of the filesystem from the HTML application but it needs to know the absolute path to the HTML.

Expected behaviour:
- Create Config
- Create Settings with ulSettingsSetFileSystemPath set to `a:\foo\`
- Create Window & View
- ulViewLoadURL 'file:///bar.html'

Actual behaviour:
- Create Config
- Create Settings with ulSettingsSetFileSystemPath set to `a:\foo\`
- Create Window & View
- ulViewLoadURL requires the full path `file:///a:/foo/bar.html`

Desired outcome:
- Create an implicit root path at the ulSettingsSetFileSystemPath so that web applications loaded from disk don't need to (and ideally can't) have any knowledge of where they are in the filesystem.

**Comment by adamjs** [comment]
Hmm, strange I can't reproduce, I just tested loading a file at `C:\Users\adam\Dev\assets\foobar\test.html` with a FileSystem root at `C:\Users\adam\Dev\assets\` and it works as expected. Here is my full code:

```
#include <AppCore/CAPI.h>

int main() {
  ULSettings settings = ulCreateSettings();
  ULString pathStr = ulCreateString("C:\\Users\\adam\\Dev\\assets\\");
  ulSettingsSetFileSystemPath(settings, pathStr);
  ulDestroyString(pathStr);

  ULConfig config = ulCreateConfig();

  ULApp app = ulCreateApp(settings, config);

  ulDestroyConfig(config);
  ulDestroySettings(settings);

  ULMonitor monitor = ulAppGetMainMonitor(app);

  ULWindow window = ulCreateWindow(monitor, 800, 600, false, kWindowFlags_Titled | kWindowFlags_Resizable);

  ulAppSetWindow(app, window);

  ULOverlay overlay = ulCreateOverlay(window, 800, 600, 0, 0);

  ULView view = ulOverlayGetView(overlay);

  ULString urlStr = ulCreateString("file:///foobar/test.html");
  ulViewLoadURL(view, urlStr);
  ulDestroyString(urlStr);

  ulAppRun(app);

  ulDestroyOverlay(overlay);

  ulDestroyWindow(window);

  ulDestroyApp(app);

  return 0;
}
```

Can you provide more code to reproduce?

And yes, we should ideally be isolating the FileSystem from access above the baseDir, right now we're just using `PathCombineW` via WinAPI to do relative path resolution on Windows but we could do more validation: https://github.com/ultralight-ux/AppCore/blob/master/src/win/FileSystemWin.cpp#L473

**Comment by Rjvs** [comment]
We're doing the same thing but unless we use the absolute path it just doesn't find the file.

In C# our code is:

```            Config = new ULConfig();
            Config.SetEnableJavaScript(true);
            Config.SetUseBGRAForOffscreenRendering(true);
            Settings = new ULSettings();
            Settings.SetFileSystemPath(BaseUri.AbsolutePath);

            App = new ULApp(Settings, Config);
            var flags = WindowFlags.Resizable | WindowFlags.Titled | WindowFlags.Borderless;
            Window = new ULWindow(App.GetMainMonitor(), 1280, 720, false, flags);
            Window.SetTitle("SL");
            App.SetWindow(Window);

            Overlay = Window.CreateOverlay(Window.GetWidth(), Window.GetHeight(), 0, 0);
            View = Overlay.GetView();

            View.LoadUrl(_htmlPath);

            View.SetDOMReadyCallback(DOMReadyInternal);
            View.SetAddConsoleMessageCallback(ConsoleMessageCallback);
            View.SetChangeURLCallback(ChangeUrlCallback);
            Window.SetResizeCallback(ResizeEventHandler);
            App.Run();
```

and the C# interop for LoadUrl is:

```        public void LoadUrl(string str) 
        {
            ULString s = ULString.CreateString(str);
            Interop.ulViewLoadURL(viewPtr, s.GetPtr());
        }
```

**Comment by Rjvs** [comment]
Where should I look for messages indicating that there is some other reason the file hasn't loaded?

**Comment by Rjvs** [comment]
@adamjs I've just confirmed the behaviour with this code:
```
            Uri uri = new Uri(Path.Join(AppDomain.CurrentDomain.BaseDirectory, "UI"));
            string _baseUri = uri.AbsoluteUri; // note: starts with "file:///d/"...
            Settings.SetFileSystemPath(_baseUri);
            View.LoadUrl( $"{_baseUri}/{screen}.html"); //works
            View.LoadUrl( $"file:///{screen}.html");  // does NOT work
```

**Comment by adamjs** [comment]
@Rjvs ah, the path that you pass to `Settings::file_system_path` should be an absolute, platform-specific local filepath. Eg, something like `C:\path\goes\here` on Windows instead of `file:///C/path/goes/here`.

You can see the implementation for how FileSystemWin resolves relative paths here: https://github.com/ultralight-ux/AppCore/blob/master/src/win/FileSystemWin.cpp#L470

Note that PathCombineW expects `baseDir` to be a native path string.

**Comment by Rjvs** [comment]
Ah, I've sorted it, thanks for the pointer -- I had a problem in my ulString C# bridge.
