### ISSUE TITLE
Add DirectX 10 support

### ISSUE THREAD

**Issue by adamjs** [ultralight-ux/Ultralight#20]
The app framework on Windows currently only supports DirectX 11.1. A DX10 port should be created so we can target more GPUs and VMs (Parallels on Mac only supports DX10.1, see #19).

**Comment by martonp96** [comment]
Hey!
This project is so cool and lightweight.
Can we get a DX9 support too?
It would be awesome if we could replace CEF in older projects.

**Comment by omascia** [comment]
I have next to zero experience with DX coding so can't probably help, but I'm in real need of DX10 driver, because its absence and the slowness of whatever AppCore elect as workaround when running on a Windows VM on Parallels Desktop, makes the whole experience of developing awful.

**Comment by adamjs** [comment]
DX9 and DX10 integration is now possible via the new Surface API in current trunk. Users can provide a lockable pixel buffer surface for the engine to draw directly into (for example, IDirect3DTexture9). 

Please see Tutorial 1 and Surface / SurfaceFactory classes in the latest bins. I'll write a D3D9 tutorial soon.
