### ISSUE TITLE
Support multiple windows

### ISSUE THREAD

**Issue by Superxwolf** [ultralight-ux/Ultralight#203]
I wrote my own GPU Driver for Windows in order to use multiple windows. The main requirement for multiple windows is associate render buffers to a specific GPU Context, which I achieved via a custom method to the GPU Driver after creating the view, and before calling Renderer->Update();

This solution proved to be good for single view per window with no opacity, but has some issues when creating/destroying views and Ultralight's re-usage of destroyed render buffer IDs. When opacity is involved this method breaks entirely and support for multiple window is required for this situations.

I think the easiest way to implement this is to be able to embed user data into the view, and be able to access the view's user data from render buffer creation.

**Comment by adamjs** [comment]
I'll be adding support for setting a GPUDriver per-View as part of the multi-monitor/multi-window changes in 1.2.

**Comment by adamjs** [comment]
Multi window support is now available in trunk.
