### ISSUE TITLE
Crash when using form-select-option tag....

### ISSUE THREAD

**Issue by colortell** [ultralight-ux/Ultralight#205]
Hi, i'm writing the demo program, and build it successfully , but when click on the select option, the program crash as the image shows.
The other issues:
- can not show checkbox;
- can not copy/paste using Command+C/V;
<img width="1149" alt="WX20191203-123021@2x" src="https://user-images.githubusercontent.com/29196899/70020823-3cbf4800-15c9-11ea-9319-fe4642ddfa9e.png">

**Comment by colortell** [comment]
<img width="1525" alt="WX20191203-123725@2x" src="https://user-images.githubusercontent.com/29196899/70020898-afc8be80-15c9-11ea-9912-88f45b2b9039.png">

**Comment by adamjs** [comment]
Latest trunk has support for radio buttons, checkboxes, and textboxes, also the dropdown crash has been fixed (though doesn't render yet). Please checkout and build locally from this repo. (This will be released shortly as 1.1)

Dropdown (selects) and platform cut/copy/paste is not yet implemented, you can find the list of features in progress here: https://github.com/ultralight-ux/Ultralight/issues/178
