### ISSUE TITLE
DirectX9

### ISSUE THREAD

**Issue by frycojsd** [ultralight-ux/Ultralight#206]
Didn’t add directx9 support yet?

**Comment by frycojsd** [comment]
Is it possible to work ultralight on a dx9?

**Comment by adamjs** [comment]
Hello! It is now possible to integrate Ultralight with DX9 via the new Surface API (you can provide a lockable pixel buffer surface for the engine to render into via the CPU renderer). See Tutorial 1 in current trunk and Surface.h in the latest bins.

**Comment by kjagosz** [comment]
Where i can find that tutorial 1? Or maybe there is some sample code

**Comment by StoneCypher** [comment]
Just open the code of this repo.  There's a samples top level directory.
