### ISSUE TITLE
Improve pixel-snapping and hairline stroke handling

### ISSUE THREAD

**Issue by adamjs** [ultralight-ux/Ultralight#208]
For sharper rendering we should snap rects, rounded rects, lines, border decorations, and non-blurred box shadows to the pixel grid when possible. (Matches behavior in Chrome, Firefox and other browser engines)

**Comment by taylorjdawson** [comment]
@adamjs where in the codebase would this be implemented?

**Comment by adamjs** [comment]
Now fixed in WebCore repo, will be integrated into main Ultralight branch soon.

**Comment by taylorjdawson** [comment]
@adamjs Awesome! Thanks!
