### ISSUE TITLE
Rendering issues with SVG clip-path

### ISSUE THREAD

**Issue by adamjs** [ultralight-ux/Ultralight#210]
Latest trunk has issues rendering certain SVGs (seems clip-path related), can be reproduced at: https://duckduckgo.com

**Comment by Deviaphan** [comment]
Another one SVG-issue:  https://stats.quake.com/profile/myztro%20VENGEUR/weapon/

![correct](https://user-images.githubusercontent.com/20601357/70534193-17b07380-1b8d-11ea-9331-74acd3320410.png)
![error](https://user-images.githubusercontent.com/20601357/70534194-17b07380-1b8d-11ea-858b-4299330f034d.png)

**Comment by adamjs** [comment]
@Deviaphan nice catch, that issue is due to unhandled `stroke-dasharray` property. I'll add it to the list
