### ISSUE TITLE
Incorrect bitmap dimension ( View::bitmap() )

### ISSUE THREAD

**Issue by Deviaphan** [ultralight-ux/Ultralight#227]
Wrong Bitmap size.
I want to add WebBrowser to MFC CDialog. I can't find native support of HWND, so I render into Bitmap and convert ultralight::Bitmap to MFC Bitmap to show in CDialog  (with programmaticaly redirect mouse events). 
Result:

![result](https://user-images.githubusercontent.com/20601357/71764958-0c006480-2f21-11ea-887e-3ff48b1fdb33.png)
![src](https://user-images.githubusercontent.com/20601357/71764959-0c006480-2f21-11ea-8c89-edd361852f07.png)

**Comment by Deviaphan** [comment]
Same transparent stripes with large image
![res](https://user-images.githubusercontent.com/20601357/71767484-4ed13500-2f3f-11ea-8f42-45c7def9c173.jpg)

**Comment by SupinePandora43** [comment]
#257

**Comment by adamjs** [comment]
This should be fixed in latest trunk with new Surface API (see Tutorial 1 for example of render-to-bitmap).
