### ISSUE TITLE
v1.0 release?

### ISSUE THREAD

**Issue by ImOnALampshade** [ultralight-ux/Ultralight#236]
What happened to the V1.0 release? It's not available on the release page, and I am having an issue (most likely in my code) that is preventing me from updating to v1.1

**Comment by uspasojevic96** [comment]
You have index of all releases at:
http://ultralightcore-bin.sfo2.cdn.digitaloceanspaces.com/
http://webcore-bin.sfo2.cdn.digitaloceanspaces.com/
http://ultralight-bin.sfo2.cdn.digitaloceanspaces.com/
http://appcore-bin.sfo2.cdn.digitaloceanspaces.com/

**Comment by adamjs** [comment]
Here are the links to the old v1.0 release:

https://ultralig.ht/ultralight-sdk-1.0-win.zip
https://ultralig.ht/ultralight-sdk-1.0-mac-v2.zip
https://ultralig.ht/ultralight-sdk-1.0-linux.tar.xz

**Comment by probablykasper** [comment]
@adamjs Any reason why it was removed from the release page?
