### ISSUE TITLE
Feature request: embedded resources

### ISSUE THREAD

**Issue by mitchpk** [ultralight-ux/Ultralight#238]
It would be great to have a feature where the assets folder can be embedded in a compiled app. Perhaps something similar to sciter's "packfolder" that generates a binary blob as a char array which can then be accessed using the file:// protocol.

**Comment by adamjs** [comment]
This is possible in the latest release (1.3.0), just override the FileSystem interface and have it pass pointers to embedded binary blobs for the relevant `file:///` request.

You can use [bin2header](https://github.com/AntumDeluge/bin2header) or similar utility to convert the files to embeddable C headers.
