### ISSUE TITLE
Cut-Copy-Paste, Undo not working

### ISSUE THREAD

**Issue by SupinePandora43** [ultralight-ux/Ultralight#254]
# Steps to reproduce:
* build UltraLight
* run `UltraLight Sample - Browser`
* enter something in url field
* select text
* press `Ctrl` + `X`
* press `Ctrl` + `V`

**Comment by JohnKlenk** [comment]
Undo was apparently never fixed.  I opened issue https://github.com/ultralight-ux/Ultralight/issues/410 for that.

**Comment by SupinePandora43** [comment]
> Undo was apparently never fixed.  I opened issue https://github.com/ultralight-ux/Ultralight/issues/410 for that.

Yes, but it's tracked in #178
