### ISSUE TITLE
Width, Height > 250 causes bug

### ISSUE THREAD

**Issue by SupinePandora43** [ultralight-ux/Ultralight#257]
# Steps to reproduce
* use render to png sample
* set `view_ = renderer_->CreateView(`**`256`**`, `**`256`**`, false)`

that's what it saves
![result](https://user-images.githubusercontent.com/36124472/83023619-923f5380-a046-11ea-91c0-e6b95d85e8a1.png)
![image](https://user-images.githubusercontent.com/36124472/83098265-9198d280-a0c3-11ea-9228-62d65e3b8ccc.png)

# where's error?
it's `308x308`
![image](https://user-images.githubusercontent.com/36124472/83023709-b438d600-a046-11ea-8663-3eb24b03aab5.png)
![image](https://user-images.githubusercontent.com/36124472/83023749-c6b30f80-a046-11ea-8b93-2c45935cc278.png)
`view->height()`,`view->width()` returns `256`, but when reading bitmap buffer it actually 308, and causes strange bug in render

**Comment by SupinePandora43** [comment]
#### `view_ = renderer_->CreateView(250, 250, false);`
![result](https://user-images.githubusercontent.com/36124472/83329109-ea719200-a2a0-11ea-8506-2a417e2ee525.png)
#### `view_ = renderer_->CreateView(251, 251, false);`
![result](https://user-images.githubusercontent.com/36124472/83329115-f78e8100-a2a0-11ea-8251-026ca17256b2.png)

**Comment by SupinePandora43** [comment]
# Workaround
`view_=renderer_->CreateView(2048,2048,false);`
`view_->Resize(512,512);`

**Comment by adamjs** [comment]
This should be fixed in latest trunk, Tutorial 1 has been updated for new Surface API.

**Comment by SupinePandora43** [comment]
ok, will try it out

**Comment by SupinePandora43** [comment]
Works
