### ISSUE TITLE
QueryWorkingSet showing up in profiler (1.2 preview)

### ISSUE THREAD

**Issue by jspohr-ubi** [ultralight-ux/Ultralight#262]
Hi,
Since upgrading to Ultralight 1.2 preview, I'm seeing QueryWorkingSet using significant amounts of CPU time.
It's being called from WTF::memoryFootprint in WebCore.dll. In the previous version of Ultralight this didn't appear in profiles. Perhaps it was intentionally enabled for the preview version, and the final DLLs won't ship with this. I just wanted to give a quick heads up in case people are wondering about performance regression in 1.2.

I'm using VS2019 on Windows 10, configuration RelWithDebugInfo. Profiling was done in VTune 2020.

**Comment by adamjs** [comment]
Thanks! This should be fixed in trunk.
