### ISSUE TITLE
No dependencies

### ISSUE THREAD

**Issue by 0xKiwan** [ultralight-ux/Ultralight#263]
Is there any way to run this as a single executable with no dll dependencies?

**Comment by SupinePandora43** [comment]
**NO**.

**Comment by adamjs** [comment]
The reason the library is not statically linked is a complication of the fact that JavaScriptCore and portions of WebCore and under LGPL 2.0 and, to prevent those LGPL’d sections from becoming infective, we distribute those bins as a separate dynamic library. (As you might be aware, LGPL code has a clause that requires developers to provide a method for others to modify and replace any LGPL code in an executable)

Beyond dynamic linkage, the only other way around this is for you to either A) provide the complete source code to your application or B) provide the object files for your application so others can relink.

I personally didn’t want to pass this onerous requirement on to end-users and so haven’t yet provided static libs but have had several requests lately and am considering options.

There is one more option that might solve this which is to package the executable in such a way that, on first run, it unpacks its internal DLL's and resources onto a locally installed path (such as %APPDATA%) and runs it from there. This allows distribution as a single-app while still respecting the spirit of the LGPL. I have plans to implement such a packager as part of Ultralight.

**Comment by 0xKiwan** [comment]
That would be absolutely perfect, can't wait! Thanks for replying
