### ISSUE TITLE
Reduce memory usage

### ISSUE THREAD

**Issue by adamjs** [ultralight-ux/Ultralight#27]
So far, the Ultralight binary and codebase has been minimized (woohoo! 25% the size of the typical Electron/CEF distributable!) but runtime memory usage has been neglected despite many opportunities to do so.

Reduce runtime memory usage to the absolute minimum up to the point that doing so would reduce performance (and even then, allow users to configure this memory vs. performance trade-off).

**Comment by niutech** [comment]
Still there is a room to improve. The fresh build of Ultralight 1.2.0 x64 release for Windows 10 uses 68MB of RAM, with only google.com opened it goes to 164MB, with cnn.com opened in the new tab it jumps to whooping 781MB and counting. I think there may be a memory leak.

**Comment by ylluminate** [comment]
@niutech what's the situation today? Still the same/similar memory profile for such scenarios?

**Comment by niutech** [comment]
@ylluminate The last I checked Ultralight 1.3.0 it still had a memory leak on cnn.com.
