### ISSUE TITLE
Context menu on right-click

### ISSUE THREAD

**Issue by niutech** [ultralight-ux/Ultralight#273]
Please add a context menu on right-click with options to: inspect selected element, copy selected text, paste it into `<input>` and `<textarea>`, search text in Google, open link in a new tab, print the page, etc. Thanks!

![Context menu](https://1.bp.blogspot.com/-n-9NEjtAOd4/XGZYTSGDEGI/AAAAAAAAKlc/iv1Rd2niAlIZWQeAmHzB7yL6VBOqMx8bACLcBGAs/s1600/contextmenu01.png)

**Comment by uspasojevic96** [comment]
As far as I know, contextmenu is implemented (the event) just nothing renders, it's up to whoever uses UL to implement that

**Comment by niutech** [comment]
Where is it and how to use it? I couldn't find `contextmenu` or `onContextMenu` in Ultralight and AppCore repo.

**Comment by uspasojevic96** [comment]
The event is there (exposed to js) and it works but you need to implement what to render

**Comment by adamjs** [comment]
Merging this issue into #197.
