### ISSUE TITLE
When to support Android and ios?

### ISSUE THREAD

**Issue by dapeng17951** [ultralight-ux/Ultralight#275]
When to support Android and ios?

**Comment by hthetiot** [comment]
You cannot use an alternative browser engine on iOS other than the one provided by Apple, chrome iOS use WKWebView like all iOS browsers. Know you know @dapeng17951. Android its open.

**Comment by adamski** [comment]
@hthetiot are you saying it's not possible to use Ultralight on iOS?

**Comment by hthetiot** [comment]
> @hthetiot are you saying it's not possible to use Ultralight on iOS?

No, I'm saying it will run on Safari engine what ever webview you use on iOS.
