### ISSUE TITLE
Explore <img> element with custom texture ID and/or shader params 

### ISSUE THREAD

**Issue by adamjs** [ultralight-ux/Ultralight#28]
Users sometimes need to embed render textures and other native elements inside their UI. Explore embedding these custom texture IDs via a custom `<img>` tag.

**Comment by glcraft** [comment]
Hi,
In the 1.0 release, is this feature available ?
If not, is it still planned ?

**Comment by adamjs** [comment]
This isn't yet available in the 1.0 release but is still planned.

**Comment by UncleGrim** [comment]
Hi, 
Any update on this issue regarding the 1.2+ release?

**Comment by adamjs** [comment]
Merging this issue into #277.
