### ISSUE TITLE
Proper Documentation

### ISSUE THREAD

**Issue by domeniko-gentner** [ultralight-ux/Ultralight#285]
I was looking for something like this, but without proper documentation, it takes ages to crawl through your code and understand how things work. You can get a basic sample running based on other samples, but good documentation is the cornerstone of any API. For example, I grasped wxWidgets as a beginner Programmer years ago pretty quick, because of their comprehensive examples. 

For example: `you can adjust this location in Config::cache_path`

This hint is great, but what does cache_path expect? The whole path? Only the part after %appdata%? I cannot tell without crawling through your code. Please think about adding proper documentation with something like Doxygen.

**Comment by adamjs** [comment]
Thanks for the feedback!

I'll update the in-header documentation to clarify that that path (and others) are absolute file paths.

FWIW most info is available in the headers (see the [Ultralight API repo](https://github.com/ultralight-ux/Ultralight-API)) and/or in the [docs website](https://docs.ultralig.ht). I'm preparing the beta for final release now so a lot of this info is being updated-- if you see any missing info just give me a heads up (I'm usually in Discord).

**Comment by domeniko-gentner** [comment]
I have found that using `Settings`  makes it a lot easier to adjust this path, since you can just set `app_name` and developer_name`.
But there are also overlaps from Settings to Config and Platform, especially when it comes to `FileSystem`. I don't get how they play together and as a result, I cannot get `LoadURL("file:///index.html")` to work. Nothing happens and there is no error message.

This is what I've tried:

```
EveApp::EveApp(std::string path, uint32_t width, uint32_t height)
{
    Settings s;
    s.app_name = "eveapp";
    s.developer_name = "tuxstash.de";
    //s.file_system_path = path.c_str();

    m_config.device_scale = 2.0;
    m_config.font_family_standard = "Times New Roman";
    m_config.resource_path = "./resources";
    m_config.use_gpu_renderer = false;

    Platform::instance().set_config(m_config);
    Platform::instance().set_logger(this);
    Platform::instance().set_font_loader(GetPlatformFontLoader());
    Platform::instance().set_file_system(GetPlatformFileSystem(path.c_str()));   

    m_app = App::Create(s);
    m_window.create(m_app, width, height);
}

// ------------------------------------->%-------------------------------------

RefPtr<Window> MainWindow::create(RefPtr<App> app, uint32_t width, uint32_t height)
{
    // Create main window
    long flags = kWindowFlags_Titled | kWindowFlags_Resizable | kWindowFlags_Maximizable;
    m_window = Window::Create(app->main_monitor(), width, height, false, flags);
    m_window->SetTitle("EveApp");
    m_window->set_listener(this);
    app->set_window(*m_window);

    // Create overlay
    // TODO: Move this to new class?
    m_overlay = Overlay::Create(*this, m_window->width(), m_window->height(), 0, 0);
    m_overlay->view()->LoadURL("file:///index.html");       
    //m_overlay->view()->LoadURL("https://google.com");

    return m_window;
}


```

**Comment by domeniko-gentner** [comment]
Okay, I have changed it to `m_overlay->view()->LoadURL("file:///assets/index.html"); ` and it worked. Contrary to the comments in the samples saying that the asset folder is used automatically.
