### ISSUE TITLE
Windows window title display error in Chinese/Japanese

### ISSUE THREAD

**Issue by YuzukiTsuru** [ultralight-ux/Ultralight#291]
OS：
Windows10 Simplified Chinese

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by adamjs** [comment]
Thanks for the report! I'll try to reproduce and fix.

**Comment by adamjs** [comment]
I can confirm this issue-- the fix requires an API change to `Window::SetTitle()` so I'll add this to the 1.3 branch.
