### ISSUE TITLE
Is this a web server?

### ISSUE THREAD

**Issue by AverageComet250** [ultralight-ux/Ultralight#315]
Is ultralight a web server, bundled with one or require Apache (or IIS) when run in a production environment.

**Comment by dzcpy** [comment]
No

**Comment by adamjs** [comment]
Hello! Not at all-- local HTML/JS/CSS resources can be loaded from disk or they can be loaded from memory via our `FileSystem` API (all `file:///` requests are routed to this handler which you can override to provide custom, in-memory responses).

**Comment by AverageComet250** [comment]
So do I have too place this in my Apache server directory

**Comment by Janrupf** [comment]
Hey there, I think you kind of misunderstood what Ultralight is.

Its not a Webserver, its more like a Web Browser! It displays web pages to the user, but it does not serve them to other browsers. Think of Ultralight as Chrome, just more lightweight, embeddable and faster.

**Comment by AverageComet250** [comment]
Thanks for the info. Also, if I was to move a unity web GL build into the assets folder, would that be enough to run the web GL build properly?
