### ISSUE TITLE
Transparent Views don't update properly if modified/changed/repainted

### ISSUE THREAD

**Issue by gtnardy** [ultralight-ux/Ultralight#319]
Hello there, (I'm editing this issue as it seems I have found exactly the cause of this problem, and I hope with those information it can be fixed!)

I've got some problems using transparent Views with translucent background of HTML elements. Some 'ghost effects' remain after the screen is changed.

Example 1: https://streamable.com/s5iyyx
Example 2: https://streamable.com/3rv5av

![image](https://user-images.githubusercontent.com/6226807/100884655-7e125e00-3490-11eb-8045-ed929330ef01.png)

First I discovered that setting Config.force_repaint = true; "solves" the problem.

Second I discovered that it seems to be caused by transparent Views (CreateView with transparent = false also "solved" the problem)

**Comment by gtnardy** [comment]
![image](https://user-images.githubusercontent.com/6226807/100877513-a77abc00-3487-11eb-986a-6e5c844de4b2.png)

Ghosting happens for more than 1 frame behind

**Comment by gtnardy** [comment]
First discovery: setting `Config.force_repaint = true;` "solves" the problem (should solve issue #318 as well).

**Comment by gtnardy** [comment]
I could notice the problem appeared after updating from 1.2.0beta to 1.2.0. Specifically after updating the file **Ultralight.dll**.

**Comment by adamjs** [comment]
This should be fixed in https://github.com/ultralight-ux/Ultralight/commit/248b91bc652a1fe4a1368845df1d988db03bb31e, can you test latest SDK and see?

**Comment by gtnardy** [comment]
Hey there! Nice!! Where can I download/test it?
