### ISSUE TITLE
Slow memory leak on constant image swapping

### ISSUE THREAD

**Issue by Superxwolf** [ultralight-ux/Ultralight#320]
By constantly swapping images, some memory leak is noticed. You can use the [following html](https://gist.github.com/Superxwolf/c0dcadea612d739464746f6b5135a6c7) and any two images, `background.jpg` and `background2.jpg`. Based off Sample 5, happens with both AppCore GPU and CPU renderer.

Occurs on both 1.2 and 1.2.1 beta.

**Comment by adamjs** [comment]
Thanks for the report! I'll investigate

**Comment by adamjs** [comment]
Should be fixed in https://github.com/ultralight-ux/Ultralight/commit/29d845f6f177bb4204b84ff57f51d3f7ca07be8b
