### ISSUE TITLE
SVG Text appears blurry

### ISSUE THREAD

**Issue by ThibaudMZN** [ultralight-ux/Ultralight#324]
Hi everyone !

When using an SVG text, the results seems extremely blurry, as seen in the middle of the knob bellow :

![image](https://user-images.githubusercontent.com/1643465/102693166-e98e5680-4218-11eb-92b5-ea40be009713.png)

I've "hacked" a way around it by setting the font-size of the text to a big number then scaling down the entire svg text with a transform, any idea why this is happening ?

Thanks !

**Comment by SupinePandora43** [comment]
these things will provide more info on problem:
1. svg file for reproducing
2. CPU or GPU renderer?
3. it is sample project? if yes - which one?

i tried to reproduce it:
1. Sample 7 & https://developer.mozilla.org/en-US/docs/Web/SVG/Element/text
```xml
<svg viewBox="0 0 240 80" xmlns="http://www.w3.org/2000/svg">
  <style>
    .small { font: italic 13px sans-serif; }
    .heavy { font: bold 30px sans-serif; }
    .Rrrrr { font: italic 40px serif; fill: red; }
  </style>

  <text x="20" y="35" class="small">My</text>
  <text x="40" y="35" class="heavy">cat</text>
  <text x="55" y="55" class="small">is</text>
  <text x="65" y="55" class="Rrrrr">Grumpy!</text>
</svg>
```
ultralight
![image](https://user-images.githubusercontent.com/36124472/102712960-9f73a680-42e6-11eb-9d9f-3c65c3059f19.png)
chrome
![image](https://user-images.githubusercontent.com/36124472/102712943-82d76e80-42e6-11eb-9319-82cb481284bc.png)
2. Sample 7 & https://www.w3schools.com/graphics/svg_text.asp
```xml
<svg height="60" width="200">
  <text x="0" y="15" fill="red" transform="rotate(30 20,40)">I love SVG</text>
</svg>
```
ultralight
![image](https://user-images.githubusercontent.com/36124472/102713094-70116980-42e7-11eb-90ad-1c09e78d6122.png)
chrome
![image](https://user-images.githubusercontent.com/36124472/102713101-7ef81c00-42e7-11eb-804f-971177653c91.png)

**Comment by ThibaudMZN** [comment]
I think the problem is coming from the fact that my viewbox was way smaller than yours (20x20) and my text was really small (fontsize 4), probably Ultralight is drawing everthing small then trying to scale it up thus creating those artifacts !

**Comment by SupinePandora43** [comment]
@ThibaudMZN it shouldn't happen
