### ISSUE TITLE
Question: How to cast a JSValue to a C++ string?

### ISSUE THREAD

**Issue by KL13NT** [ultralight-ux/Ultralight#327]
I'm trying to use an event handler declared in my C++ code. The function signature is 
```cpp
JSValueRef OnButtonClick(JSContextRef ctx, JSObjectRef function, JSObjectRef thisObject, size_t argumentCount, const JSValueRef arguments[], JSValueRef* exception)
``` 

What I want to do is use the arguments array and cast the parameters (which will be passed from JS as strings) into C++ strings. Is this possible? 

I tried casting it to a `char *` but it didn't work, and frankly I'm not that much of a CPP pro.

**Comment by AverageComet250** [comment]
I'm not fully sure what the code you wrote does and where function parameters exist, but I should probably tell you that `char` doesn't exist in JS and it has `str` instead, meaning that you should pass a string in JavaScript by giving data enveloped in quotes and then (if ultralight doesn't do it already do it) convert it too format `char` in your c++ code.

I'd also recommend using Typescript as your variables can be explicitly declared as strings, integers and floats however you'll need to use tsc (`npm install tsc` more info is available on the ms docs) to compile it into JS

**Comment by Janrupf** [comment]
For converting a `JSValueRef` to a `std::string`:
```cpp
        JSContextRef ctx = ...;
        JSValueRef value = ...;
        
        // Convert the JSValueRef to a string (may fail)
        JSValueRef exception = nullptr;
        JSStringRef string_ref = JSValueToStringCopy(ctx, value, &exception);
        if(exception) {
            // TODO: Handle
            return nullptr;
        }

        // Convert the JSStringRef to a C++ string (method given below)
        std::string cpp_string = create_utf8_from_jsstring_ref(env, string_ref);
        
        // Release the string, it has been copied and is not longer required
        JSStringRelease(string_ref);
```
For converting a `JSStringRef` to a `std::string`:
```cpp
    std::string create_utf8_from_jsstring_ref(JSStringRef str) {
        // Get the maximum conversion length
        size_t buffer_size = JSStringGetMaximumUTF8CStringSize(str);

        if(buffer_size < 1) {
            // Check for 0 length
            return "";
        }

        // Allocate a buffer to store the data in
        char *buffer = new char[buffer_size];

        // Convert the string
        size_t real_size = JSStringGetUTF8CString(str, buffer, buffer_size);

        // Copy the buffer length into a std::string
        // This constructor takes the length without the null byte
        std::string ret(buffer, real_size - 1);

        // Clean up and return
        delete[] buffer;
        return ret;
    }
```

**Comment by KL13NT** [comment]
That should work, thanks for the help!
