### ISSUE TITLE
Game Physics best location

### ISSUE THREAD

**Issue by AverageComet250** [ultralight-ux/Ultralight#335]
When making a game using ultralight, I would put my UI in html obviously. But where am I best suited putting movement scripts and other physics code?

From what I can work out, using a custom physics engine in c++ is best, and things like movement are beat off as c++ commands called from JavaScript.

But what is the best way to do this?

**Comment by SupinePandora43** [comment]
handle movement and physics in c++
use html for hud/gui etc...

// this is not valid issue

**Comment by AverageComet250** [comment]
Yeah I realised that I should have asked this in the discord.
