### ISSUE TITLE
Feature request: Add "ULString to UTF8" conversion function to C API

### ISSUE THREAD

**Issue by kumikumi** [ultralight-ux/Ultralight#355]
Currently there is a way to construct a ULString from UTF8 data, but no way to do the reverse i.e. get UTF8 data from a ULString.

**Comment by SupinePandora43** [comment]
Fixed in 1.3: ultralight::`String` is now ultralight::`String8`.
But now you can't get utf16 out of it :P

**Comment by adamjs** [comment]
It has indeed been fixed in 1.3.0, UTF-8 is now the default in the API (<https://ultralig.ht/api/c/1_3_0/_c_a_p_i___string_8h.html>), I'll expose the UTF-16 and UTF-32 conversion ops later.
