### ISSUE TITLE
FireMouseEvent seems to be discarding events

### ISSUE THREAD

**Issue by ostwilkens** [ultralight-ux/Ultralight#362]
Mouse events sent with `FireMouseEvent` seem to be discarded if the coordinates leave the viewport. 
There are cases where you want to handle mouse events, even though the cursor is not currently inside the bounding box. 
It would be great if it was up to the developer to discard the events if needed, or if an option was added to toggle this.

**Comment by adamjs** [comment]
I think I'll need a little more information to diagnose what's going wrong here.

Are you using AppCore to handle the mouse events? Which platform is the behavior on?

I set up a little test with AppCore (on Windows 10) by loading the following code into a standard `Window` + `Overlay` to compare differences side-by-side with Chrome.

```
<!DOCTYPE html>
<html>
    <head>
    </head>
    <body>
        <p id="coords"></p>
        <p id="mouse-state"></p>

        <script>
        function $(x) { return document.getElementById(x); }

        function mouseMove(e) {
            var x = e.clientX;
            var y = e.clientY;
            $("coords").innerHTML = "Coordinates: (" + x + "," + y + ")";
        }

        function mouseEnter() {
            $("mouse-state").innerHTML = "MouseOver";
        }

        function mouseLeave() {
            $("mouse-state").innerHTML = "MouseOut";
        }

        function init() {
            document.addEventListener("mousemove", mouseMove, false);
            document.addEventListener("mouseover", mouseEnter, false);
            document.addEventListener("mouseout", mouseLeave, false);
        }

        init();
        </script>
    </body>
</html>
```

When the mouse leaves the window, the `coordinates` do not get updated. However, when the mouse button is pressed and held down while leaving the window (eg, a "drag"), the displayed `coordinates` continuously update (even when the mouse pointer is outside the viewport) until the mouse button is released. This behavior matches Chrome.

AFAIK there's no logic inside `FireMouseEvent` to discard mouse events outside the viewport, internally it is calling [EventHandler::mouseMoved()](https://github.com/ultralight-ux/WebCore/blob/8d2d86c6bceb1bc9f630fad1e37c40fa980c3be4/Source/WebCore/page/EventHandler.cpp#L1926) if you want to trace it in a debugger (you'll need to build WebCore for debug first).

At the AppCore level we do some special handling to make sure that the OS continues to send us mouse events while the mouse button is held down, [see `ultralight::WindowWin`](https://github.com/ultralight-ux/AppCore/blob/3c460e10c062ee9f0c45c136ee8bbe970e5f7fb5/src/win/WindowWin.cpp#L103).

**Comment by ostwilkens** [comment]
We are using ultralight directly, utilizing the `ultralight::View` class. 
I read through [ViewDelegate](https://github.com/ultralight-ux/AppCore/blob/722e157441827ffb8844adfda843260c8f0efa46/src/mac/ViewDelegate.mm) in AppCore and saw that it keeps a state for the mouse button in `_cur_button`. I didn't realize this was needed. I implemented a similar state in our application and things are now working as expected. Thanks for pointing me in the right direction!
