### ISSUE TITLE
UTF8 string length inconsistency

### ISSUE THREAD

**Issue by SupinePandora43** [ultralight-ux/Ultralight#409]
`String8`:
> `size_t​ ​sizeBytes​() ​const​ { ​return​ length_ * ​sizeof​(​char​); }`

UTF8 can use **up to 4 bytes** per character.

This code is right for Ansi encoding, but not for UTF8.

**Comment by LoganDark** [comment]
The method name is literally size**Bytes**. Therefore, it returns the size in **bytes**, not **Unicode codepoints**.

**Comment by SupinePandora43** [comment]
> The method name is literally size**Bytes**. Therefore, it returns the size in **bytes**, not **Unicode codepoints**.

What?

**Comment by LoganDark** [comment]
> > The method name is literally size**Bytes**. Therefore, it returns the size in **bytes**, not **Unicode codepoints**.
> 
> What?

UTF-8 _can_ use multiple bytes per Unicode codepoint, but since the size**Bytes** function returns **bytes**, it doesn't have to parse the string for UTF-8, because bytes don't care about what encoding you use.

Take this string for example: "ͰΞΟA", which is `cd b0 ce 9e ce 9f 41` in hex. Its size in characters, or codepoints, is 4, however its size in bytes is 7. `sizeBytes` returns bytes, so it should return 7, not 4.

**Comment by SupinePandora43** [comment]
> > > The method name is literally size**Bytes**. Therefore, it returns the size in **bytes**, not **Unicode codepoints**.
> > 
> > 
> > What?
> 
> UTF-8 _can_ use multiple bytes per Unicode codepoint, but since the size**Bytes** function returns **bytes**, it doesn't have to parse the string for UTF-8, because bytes don't care about what encoding you use.
> 
> Take this string for example: "ͰΞΟA", which is `cd b0 ce 9e ce 9f 41` in hex. Its size in characters, or codepoints, is 4, however its size in bytes is 7. `sizeBytes` returns bytes, so it should return 7, not 4.

Yes. It should return `7`.

**Comment by LoganDark** [comment]
> Yes. It should return `7`.

Does it not currently?

**Comment by SupinePandora43** [comment]
> > Yes. It should return `7`.
> 
> Does it not currently?

It is, but length is incorrect then

**Comment by LoganDark** [comment]
> It is, but length is incorrect then

How so? It's normal for some strings to store their length in a separate variable. That way you can have embedded nulls and you don't need a null terminator.

**Comment by SupinePandora43** [comment]
> > It is, but length is incorrect then
> 
> How so? It's normal for some strings to store their length in a separate variable. That way you can have embedded nulls and you don't need a null terminator.

It's byte length, but not character length 🥴

**Comment by LoganDark** [comment]
> It's byte length, but not character length 🥴

Yes...? You don't use character length when allocating blocks of memory or transferring data between systems. I'm sure there's a dedicated utility function for calculating the UTF8 string length in characters.
