### ISSUE TITLE
Help with Getting Started Tutorial

### ISSUE THREAD

**Issue by SantosJMM** [ultralight-ux/Ultralight#422]
Greetings, I would like to try this wonderful project and I have found an error that although simple I have not been able to solve and I would like to know if someone can help me. Below I leave the error that throws me.

My system is ArchLinux x86_64 GNU/Linux

[ 72%] Built target UltralightSDK
[ 81%] Linking CXX executable MyApp
/usr/bin/ld: warning: libpcre.so.3, needed by /home/smarte/testing/ultralight-quick-start/build/SDK/bin/libglib-2.0.so.0, not found (try using -rpath or -rpath-link)
/usr/bin/ld: /home/smarte/testing/ultralight-quick-start/build/SDK/bin/libglib-2.0.so.0: undefined reference to `pcre_exec'
/usr/bin/ld: /home/smarte/testing/ultralight-quick-start/build/SDK/bin/libglib-2.0.so.0: undefined reference to `pcre_study'
/usr/bin/ld: /home/smarte/testing/ultralight-quick-start/build/SDK/bin/libglib-2.0.so.0: undefined reference to `pcre_dfa_exec'
/usr/bin/ld: /home/smarte/testing/ultralight-quick-start/build/SDK/bin/libglib-2.0.so.0: undefined reference to `pcre_fullinfo'
/usr/bin/ld: /home/smarte/testing/ultralight-quick-start/build/SDK/bin/libglib-2.0.so.0: undefined reference to `pcre_get_stringnumber'
/usr/bin/ld: /home/smarte/testing/ultralight-quick-start/build/SDK/bin/libglib-2.0.so.0: undefined reference to `pcre_free'
/usr/bin/ld: /home/smarte/testing/ultralight-quick-start/build/SDK/bin/libglib-2.0.so.0: undefined reference to `pcre_config'
/usr/bin/ld: /home/smarte/testing/ultralight-quick-start/build/SDK/bin/libglib-2.0.so.0: undefined reference to `pcre_compile2'
/usr/bin/ld: /home/smarte/testing/ultralight-quick-start/build/SDK/bin/libglib-2.0.so.0: undefined reference to `pcre_get_stringtable_entries'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/MyApp.dir/build.make:113: MyApp] Error 1
make[1]: *** [CMakeFiles/Makefile2:111: CMakeFiles/MyApp.dir/all] Error 2
make: *** [Makefile:91: all] Error 2

**Comment by SupinePandora43** [comment]
Quick start is outdated and broken

**Comment by SantosJMM** [comment]
@SupinePandora43 Thank you very much, then I think I'll close the issue
