### ISSUE TITLE
Issue with C API: ulPlatformSetFileSystem

### ISSUE THREAD

**Issue by adamjs** [ultralight-ux/Ultralight#428]
`ulPlatformSetFileSystem()` (and other platform-related C-API calls) fail to synchronously set the underlying filesystem if the Renderer is wrapped to C-API calls prior to the call.

**Comment by SupinePandora43** [comment]
Do you mean that c filesystem (and others) are set **after** `ulCreateRenderer`?

**Comment by adamjs** [comment]
Fixed in trunk.
