### ISSUE TITLE
SurfaceFactory::CreateSurface called twice by renderer->CreateView()

### ISSUE THREAD

**Issue by Northn** [ultralight-ux/Ultralight#430]
For some unknown reasons, if we create own SurfaceFactory and pass it to `Platform::instance().set_surface_factory()`, when we create a view by CreateView, SurfaceFactory::CreateSurface is getting called twice: at first time it gets corresponding width and height, but at second call it always gets width and height to be 10. Is it a bug of 1.3.0?
Steps to reproduce: Simple use OpenGL sample and add `std::cout << "Asking to create a new surface: " << width << '\t' << height << '\t' << std::endl;` to `GLTextureSurfaceFactory::CreateSurface()`
![image](https://user-images.githubusercontent.com/57762732/176749186-0a1ee621-b7a0-44cb-bd2d-3bc223d09522.png)

**Comment by Northn** [comment]
Update: It seems second surface is getting created to render dropdowns, but it doesn't have to be, it should render immediarely to texture itself
I've tried to render texture from second surface and my theory was confirmed, it's really getting created for dropdowns
![image](https://user-images.githubusercontent.com/57762732/176952763-25a456df-5542-40f7-92ca-871c841e3bd9.png)
So, this issue: https://github.com/ultralight-ux/Ultralight/issues/427 seems to be related to this issue

**Comment by adamjs** [comment]
Views no longer eagerly create surfaces to render dropdowns in the latest release (1.3.0).
