### ISSUE TITLE
static build option.

### ISSUE THREAD

**Issue by leftspace89** [ultralight-ux/ultralight#45]
there is no static build option 👎 
so why should we use this black box library ? 

even sample browser app crashing randomly.

**Comment by movqword** [comment]
@leftspace89 with regards, but what will be changed when you will get static library - it's too will be closed-source 'black box', if type of this project is not suitable for you - free to find something else.

**Comment by leftspace89** [comment]
if I got static library I can make standalone single executable. Im not using electron because of too many files there Im searching new alternatives  sad for me.
are you selling this library  ?  no 
are you planning  sell this library ? 

why its closed-source ? community can't help you because of that I saw your awesomium library its closed source too.

**Comment by movqword** [comment]
@leftspace89 

First - it's not my project, but project of [Adam](https://github.com/adamjs).

Next - type of project is not thread for discuss, you can only select suitable it's for you or no, all other is controversy about tastes, very strange to see something like your words, seems you old man, but not child. Founder of project think that this type (closed source) is good for business, but you think that it's bad for using, so seems you create 'issue' just for notify all about your own opinion.

With best regards.

**Comment by codecat** [comment]
This has nothing to do with Open/Closed source, but with the LGPL license [that webkit uses](https://webkit.org/licensing-webkit/). That's why static linking will not be possible.
