### ISSUE TITLE
Mouse hovering link sets cursor to kCursor_Hand then back do kCursor_Pointer (Browser sample)

### ISSUE THREAD

**Issue by itsbrainmeat** [ultralight-ux/Ultralight#49]
In Browser sample, when hovering the mouse over a link, the cursor changes to **kCursor_Hand** and immediately back to **kCursor_Pointer**.

**Steps to Reproduce**
- Slowly drag the mouse pointer to a link until you see a mouse cursor change
- Observe the pointer change to the hand cursor
- If you move the mouse cursor just a bit it will change to the pointer again

**Looks like:**
- "onMouseEnter" -> sets cursor to hand
- "onMouseOver" -> bug, sets back to pointer (default?)
- "onMouseExit" -> resets
- "onMouseEnter" (again) -> sets cursor to hand
- ....

**Platform Info:**
 - OS: Windows 10
 - SDK Version 0.9.1

**Comment by APerricone** [comment]
Windows need setcursor called continuously so the check that the cursor changes in  https://github.com/ultralight-ux/AppCore/blob/cb4899e9f19236b13241fb5bf370d1e9d905ca79/src/win/WindowWin.cpp#L230
generates the error.

It is pretty simple to fix, do you want a pull request?

**Comment by adamjs** [comment]
Should be fixed in current trunk.
