### ISSUE TITLE
Nintendo Switch support

### ISSUE THREAD

**Issue by StoneCypher** [ultralight-ux/ultralight#493]
In keeping with #216, I was wondering whether support for the Nintendo Switch was slated

You mention that ARM64 is inbound in 1.4, and Switch is ARM64, and I don't know that any other current major game consoles are, so, I have some hope

**Comment by adamjs** [comment]
Hello! Yes, Switch support is planned for 2024, beyond ARM64 support we're working on some new features to improve JS performance and interop on low-power devices.

**Comment by StoneCypher** [comment]
great
