### ISSUE TITLE
Mac Example doesn't work

### ISSUE THREAD

**Issue by eduhh94** [ultralight-ux/ultralight#51]
**Summarize the Issue**
https://github.com/ultralight-ux/ultralight/blob/master/samples/HelloWorld/src/main.cc
'../../../framework/platform/common/FontLoaderRoboto.h' file not found

**Steps to Reproduce**
Xcode 10

**Platform Info:**
MacOs 10.14

**Comment by faaip** [comment]
@eduhh94 , did you manage to find a solution for this?
