### ISSUE TITLE
HTTP Public Key Pinning

### ISSUE THREAD

**Issue by isoadam** [ultralight-ux/Ultralight#52]
**Describe the solution you'd like**
Create and expose an API to allow implementations to secure HTTPS requests against approved keys.

**Describe alternatives you've considered**
Using the LoadHTML to only load pages/content you've secured/verified - doesn't work with XHR.

**Comment by adamjs** [comment]
In latest branch (1.2) we bundle certificates via `resource/cacert.pem` which contains a list of certificates extracted from Mozilla's latest store (see https://curl.haxx.se/docs/caextract.html). You can customize this file to bundle your own certs.
