### ISSUE TITLE
style "letter-spacing" does not work

### ISSUE THREAD

**Issue by cfadamp** [ultralight-ux/ultralight#53]
**Summarize the Issue**
I tried to use style "letter-spacing" for texts but it seems like this feature does not work.

**Steps to Reproduce**
Sample code which can demonstrate the issue:
```
<html>
	<body bgcolor="#000000">
		<div style="background-color: rgb(0, 0, 0); width: 2112px; height: 1088px; ">
			<div style="height: 1016px; width: 1984px; top: 36px; left: 64px;">
				<span style="background-color: rgba(0, 0, 0, 0); color: rgba(255, 255, 255, 1);  font-size: 57.3px; visibility: visible; letter-spacing: 10px; ">Sample text and some more text</span>
			</div>
		</div>
	</body>
</html>
```

SDK should render the spaces between the letters.

**Platform Info:**
 - OS: tried on Windows only
 - SDK Version 0.9

**Comment by adamjs** [comment]
Thanks for the report, was able to reproduce-- a fix will be included in the official release of 0.9.2.
