### ISSUE TITLE
Missing include file Ultralight/Vector.h

### ISSUE THREAD

**Issue by MPKaboose** [ultralight-ux/ultralight#64]
**Summarize the Issue**
Missing include file Ultralight/Vector.h

**Steps to Reproduce**
Include Ultralight/Ultralight.h and compile.

**Platform Info:**
 - OS: Windows
 - SDK Version: 0.9*

The required include file is missing from both GitHub and the Windows/Linux SDK, unless I'm missing something.

**Comment by edwardstock** [comment]
@MPKaboose the same, but i think they removed it
https://github.com/ultralight-ux/ultralight/pull/32

**Comment by movqword** [comment]
All right, this happens only with SDK package published on the website, becouse it's still not updated (while in active progress 0.9.2), but you can clone or download latest GitHub version. 

P.S.: Or you can remove include line from Ultralight.h, Vector.h has been removed at all, so you not will get any compile error if skip it.

With best regards.

**Comment by MPKaboose** [comment]
Sorry I was away for a few days, yes that makes sense now, I also found that the file `JavaScriptCore/JavaScriptCore.h` was renamed to `JavaScriptCore/JavaScript.h`

**Comment by MPKaboose** [comment]
I think this can be closed now, regards.
