### ISSUE TITLE
Does Ultralight support frameworks like React?

### ISSUE THREAD

**Issue by mike168m** [ultralight-ux/ultralight#69]
Are there any modifications to the engine that stop it from supporting modern web frameworks developers should know about?

**Comment by KenanSulayman** [comment]
Yes, of course it supports React..

**Comment by SalahAdDin** [comment]
Yeah, but how?

**Comment by joepriit** [comment]
> Yeah, but how?

Just transpile the project, if you're using TypeScript, and use view()->LoadURL('path/to/index.html') to load it on the Overlay.
I'm using the Angular framework, but I doubt there's any significant difference to be honest.
