### ISSUE TITLE
Slack / discord community?

### ISSUE THREAD

**Issue by shawwn** [ultralight-ux/ultralight#7]
I was hoping to hop in and say hello somewhere.

**Comment by shawwn** [comment]
(To be precise, do you need someone to set up a Slack or Discord? I set up ParcelJS's.)

**Comment by theTwist84** [comment]
There is already a [Slack ](https://chat.ultralig.ht/)

**Comment by adamjs** [comment]
Pretty sure you found your way to the Slack chatroom so I'm going to say this one's closed. :)

**Comment by shawwn** [comment]
Ah, yep, forgot to close this. Thanks!
