### ISSUE TITLE
JSHelpers.h - JSValue cannot be overloaded 

### ISSUE THREAD

**Issue by pacampbell** [ultralight-ux/Ultralight#74]
**Summarize the Issue**

While following the steps to build for Linux, a build issue occurs which states `JSValue cannot be overloaded`. 

**Platform Info**
OS: Ubuntu 18.04.1 LTS
gcc: (Ubuntu 7.3.0-27ubuntu1\~18.04) 7.3.0
g++: (Ubuntu 7.3.0-27ubuntu1\~18.04) 7.3.0
sdk-version: 1.9.1

**Steps to Reproduce**
Follow build instructions to generate Makefile with cmake and type `make`.

```
In file included from /home/pacampbell/Git/ultralight-sdk/ultralight-1.9.1/samples/Browser/src/UI.h:4:0,
                 from /home/pacampbell/Git/ultralight-sdk/ultralight-1.9.1/samples/Browser/src/Browser.h:4,
                 from /home/pacampbell/Git/ultralight-sdk/ultralight-1.9.1/samples/Browser/src/Browser.cc:1:
/home/pacampbell/Git/ultralight-sdk/ultralight-1.9.1/deps/Framework/JSHelpers.h:108:4: error: ‘framework::JSValue::JSValue(long unsigned int)’ cannot be overloaded
    JSValue(unsigned long val);
    ^~~~~~~
/home/pacampbell/Git/ultralight-sdk/ultralight-1.9.1/deps/Framework/JSHelpers.h:102:3: error: with ‘framework::JSValue::JSValue(uint64_t)’
   JSValue(uint64_t val);
   ^~~~~~~
samples/Browser/CMakeFiles/Browser.dir/build.make:62: recipe for target 'samples/Browser/CMakeFiles/Browser.dir/src/Browser.cc.o' failed
```

**Analysis**

Taking a look at `JSHelpers.h`, it seems that line 102 and line 108 describe the same overload.

`JSHelpers.h:102: JSValue(uint64_t val);`
`JSHelpers.h:108: JSValue(unsigned long val);`

Looking at output of `g++ -E` I can see that `uint64_t` is typedef'ed to `typedef __uint64_t uint64_t;` which is typedef'ed to `typedef unsigned long int __uint64_t;`. I may be wrong, but I believe that `unsigned long int` and `unsigned long` evaluate to the same thing in this situation.

If i had to guess, on Windows, `unsigned long int` is actually a 32-bit value (4 bytes), where as in x64 Linux it is a 64-bit value (8 bytes). Since `inttype.h` defines uint64_t for whatever the 64-bit size is for the platform, this gives no issues on Windows since uint64_t is probably `unsigned long long int` but gives an issue in Linux for the above reasoning. 

**Naive fix**

Without access to a Windows development machine, this may not be perfect, but removing the following allows it to build on my system:

```
JSHelpers.h:108: JSValue(unsigned long val);
JSHelpers.cpp:90: JSValue::JSValue(unsigned long val) : ctx_(GetJSContext())
```

**Comment by adamjs** [comment]
Thanks, this was fixed some months ago.
