### ISSUE TITLE
[Platform request] Consoles (Xbox / PS4) and Smart TVs (WebOS, Tizen, etc)

### ISSUE THREAD

**Issue by matthew-dean** [ultralight-ux/Ultralight#77]
This seems like a really needed project. Some questions: are there any plans to support console builds (Xbox / PS4), or builds for Smart TVs? That's a really underserved market.

**Comment by gdeverlant** [comment]
I think you should have a look at Haxe with OpenFL maybe you will find out what you are looking for.

**Comment by adamjs** [comment]
Xbox, PS4, and PS5 support is now available in the latest stable release (1.3.0). Support for ARM64 platforms will be available in 1.4.X.
