### ISSUE TITLE
Don't include Windows.h

### ISSUE THREAD

**Issue by ImOnALampshade** [ultralight-ux/ultralight#81]
**Is your feature request related to a problem? Please describe.**
Currently, Windows.h is included by Ultralight/KeyEvent.h. There is no WIN32_LEAN_AND_MEAN or NO_MINMAX macro defined before it, which means it is completely unminimized. Windows.h is known to pollute namespaces, break builds, and lengthen compile times, and should definitely not be included in a header if it can at all be avoided.

**Describe the solution you'd like**
Windows.h is only included by one file, and only needed for one function (`KeyEvent::KeyEvent()`). It is needed in order to define LPARAM and WPARAM types for the paramters of that function. Instead of doing all that, why not just use `unsigned int` or `unsigned __int64` directly (Depending on architecture)? This removes the need for `Windows.h` to be included without breaking any functionality,

**Describe alternatives you've considered**
While I can (and have) done the change described above to the header file in my own build system, this change should be Incorporated into the official release of ultralight.

**Comment by ImOnALampshade** [comment]
If it helps, here is my modified `KeyEvent.h`
[KeyEvent.zip](https://github.com/ultralight-ux/ultralight/files/2888556/KeyEvent.zip)

**Comment by SlidyBat** [comment]
Agree that Windows.h shouldn't be included, my solution was to use the following typedefs instead:
```cpp
typedef intptr_t  LPARAM;
typedef uintptr_t WPARAM;
```

**Comment by adamjs** [comment]
It's a reasonable request, I'll add it. Thanks.
