### ISSUE TITLE
Mac OS/CMake: Duplicate rule when using Ninja

### ISSUE THREAD

**Issue by IngwiePhoenix** [ultralight-ux/ultralight#85]
**Summarize the Issue**
By default, I use the Ninja generator (since it is faster due to parallelization and because I have the CPU to run this properly) and did so when I wanted to build this project.

**Steps to Reproduce**
```
Ingwie@Ingwies-MBP.fritz.box ~/W/Git $ git clone --recursive https://github.com/ultralight-ux/ultralight.git
Klone nach 'ultralight' ...
remote: Enumerating objects: 176, done.
remote: Counting objects: 100% (176/176), done.
remote: Compressing objects: 100% (126/126), done.
remote: Total 1949 (delta 72), reused 117 (delta 44), pack-reused 1773
Empfange Objekte: 100% (1949/1949), 170.98 MiB | 4.59 MiB/s, Fertig.
Löse Unterschiede auf: 100% (909/909), Fertig.
Checke Dateien aus: 100% (344/344), Fertig.
Ingwie@Ingwies-MBP.fritz.box ~/W/Git $ cd ultralight/
Ingwie@Ingwies-MBP.fritz.box ~/W/G/ultralight $ mkdir out
Ingwie@Ingwies-MBP.fritz.box ~/W/G/ultralight $ cd out
Ingwie@Ingwies-MBP.fritz.box ~/W/G/u/out $ cmake -G Ninja ..
-- The C compiler identification is AppleClang 10.0.0.10001145
-- The CXX compiler identification is AppleClang 10.0.0.10001145
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/Ingwie/Work/Git/ultralight/out
Ingwie@Ingwies-MBP.fritz.box ~/W/G/u/out $ ninja
ninja: error: build.ninja:466: multiple rules generate ../samples/Info.plist.in [-w dupbuild=err]
```

**Platform Info:**
 - OS: 
```
ProductName:	Mac OS X
ProductVersion:	10.14.3
BuildVersion:	18D109
```
 - SDK Version
```
$ git rev-parse HEAD
91298b7c0670f253a9a587e69cee1edb2cb920c1
```

**Comment by adamjs** [comment]
Thanks for this, I'll fix.

**Comment by moebiussurfing** [comment]
same error here using Sierra

**Comment by moebiussurfing** [comment]
sorry but, when I click to compiled apps Browser.app / Tutorial2.app... , the icon flashes but app windows is not opening.

`cmake --build . --config Release
Scanning dependencies of target Browser
[  7%] Building CXX object samples/Browser/CMakeFiles/Browser.dir/src/Browser.cpp.o
[ 15%] Building CXX object samples/Browser/CMakeFiles/Browser.dir/src/Tab.cpp.o
[ 23%] Building CXX object samples/Browser/CMakeFiles/Browser.dir/src/UI.cpp.o
[ 30%] Building CXX object samples/Browser/CMakeFiles/Browser.dir/src/main.cpp.o
[ 38%] Linking CXX executable Browser.app/Contents/MacOS/Browser
[ 38%] Built target Browser
Scanning dependencies of target Tutorial1
[ 46%] Building CXX object samples/Tutorial 1 - Render to PNG/CMakeFiles/Tutorial1.dir/main.cpp.o
[ 53%] Linking CXX executable Tutorial1
[ 53%] Built target Tutorial1
Scanning dependencies of target Tutorial2
[ 61%] Building CXX object samples/Tutorial 2 - Basic App/CMakeFiles/Tutorial2.dir/main.cpp.o
[ 69%] Linking CXX executable Tutorial2.app/Contents/MacOS/Tutorial2
[ 69%] Built target Tutorial2
Scanning dependencies of target Tutorial3
[ 76%] Building CXX object samples/Tutorial 3 - Resizable App/CMakeFiles/Tutorial3.dir/main.cpp.o
[ 84%] Linking CXX executable Tutorial3.app/Contents/MacOS/Tutorial3
[ 84%] Built target Tutorial3
Scanning dependencies of target Tutorial4
[ 92%] Building CXX object samples/Tutorial 4 - JavaScript/CMakeFiles/Tutorial4.dir/main.cpp.o
[100%] Linking CXX executable Tutorial4.app/Contents/MacOS/Tutorial4
[100%] Built target Tutorial4
`

`myMacBook:out myUser$ cmake -G Ninja ..
-- The C compiler identification is AppleClang 8.1.0.8020042
-- The CXX compiler identification is AppleClang 8.1.0.8020042
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/myUser/Documents/JS/ultralight/out`

as you can see I tried with bot cmake and ninja.

**Comment by moebiussurfing** [comment]
@adamjs also, there is some way to create Xcode projects por any sample?

ps: 

> cmake version 3.14.0
> CMake suite maintained and supported by Kitware (kitware.com/cmake).

> gcc --version
> Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
> Apple LLVM version 8.1.0 (clang-802.0.42)
> Target: x86_64-apple-darwin16.7.0
> Thread model: posix
> InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

> clang -v
> Apple LLVM version 8.1.0 (clang-802.0.42)
> Target: x86_64-apple-darwin16.7.0
> Thread model: posix
> InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

> llvm-gcc -v
> Apple LLVM version 8.1.0 (clang-802.0.42)
> Target: x86_64-apple-darwin16.7.0
> Thread model: posix
> InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
 
> xcodebuild -version
> Xcode 8.3.3
> Build version 8E3004b

> MacOS Sierra 10.12.6

**Comment by adamjs** [comment]
This seems like a separate issue, can you make a new issue with a stack trace? Also you can generate Xcode projects by running the following from your build directory: `cmake .. -G "Xcode"`

**Comment by moebiussurfing** [comment]
ok. thanks

> This seems like a separate issue, can you make a new issue with a stack trace? Also you can generate Xcode projects by running the following from your build directory: `cmake .. -G "Xcode"`

> cmake .. -G "Xcode"
> CMake Error: Error: generator : Xcode
> Does not match the generator used previously: Unix Makefiles
> Either remove the CMakeCache.txt file and CMakeFiles directory or choose a different binary directory.

**Comment by moebiussurfing** [comment]
I am tring again with the https://gitlab.com/dasoe/ofxultralight :

> cmake .. -G "Xcode9"
> CMake Error: Could not create named generator Xcode9
>  
> Generators
> * Unix Makefiles               = Generates standard UNIX makefiles.
>   Ninja                        = Generates build.ninja files.
>   Xcode                        = Generate Xcode project files.
>   CodeBlocks - Ninja           = Generates CodeBlocks project files.
>   CodeBlocks - Unix Makefiles  = Generates CodeBlocks project files.
>   CodeLite - Ninja             = Generates CodeLite project files.
>   CodeLite - Unix Makefiles    = Generates CodeLite project files.
>   Sublime Text 2 - Ninja       = Generates Sublime Text 2 project files.
>   Sublime Text 2 - Unix Makefiles
>                                = Generates Sublime Text 2 project files.
>   Kate - Ninja                 = Generates Kate project files.
>   Kate - Unix Makefiles        = Generates Kate project files.
>   Eclipse CDT4 - Ninja         = Generates Eclipse CDT 4.0 project files.
>   Eclipse CDT4 - Unix Makefiles= Generates Eclipse CDT 4.0 project files.

**Comment by IngwiePhoenix** [comment]
Just use XCode, not XCode9.

this should pick up the XCode you have installed…there might be a variable you can set to change the installation being used, if you have multiple ones installed.

**Comment by moebiussurfing** [comment]
yes sorry, I used XCode too. my mistake when copy/paste.
```
build user$ cmake .. -G "Xcode"
CMake Error: Error: generator : Xcode
Does not match the generator used previously: Unix Makefiles
Either remove the CMakeCache.txt file and CMakeFiles directory or choose a different binary directory.
```
 Do you mean should I rename my Xcode9.app too? I had Xcode 8 previously too, that's why the name

**Comment by moebiussurfing** [comment]
CMakeCache.txt looks like this:

> # This is the CMakeCache file.
> # For build in directory: /Users/manumolina/Documents/openFrameworks/addons/ofxultralight/libs/ultralight/build
> # It was generated by CMake: /usr/local/Cellar/cmake/3.14.0/bin/cmake
> # You can edit this file to change values found and used by cmake.
> # If you do not want to change any of the values, simply exit the editor.
> # If you do want to change a value, simply edit, save, and exit the editor.
> # The syntax for the file is as follows:
> # KEY:TYPE=VALUE
> # KEY is the name of a variable in the cache.
> # TYPE is a hint to GUIs for the type of VALUE, DO NOT EDIT TYPE!.
> # VALUE is the current value for the KEY.
> 
> ########################
> # EXTERNAL cache entries
> ########################
> 
> //Path to a program.
> CMAKE_AR:FILEPATH=/Applications/Xcode9.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar
> 
> //Choose the type of build, options are: None Debug Release RelWithDebInfo
> // MinSizeRel ...
> CMAKE_BUILD_TYPE:STRING=
> 
> //Enable/Disable color output during build.
> CMAKE_COLOR_MAKEFILE:BOOL=ON
> 
> //CXX compiler
> CMAKE_CXX_COMPILER:FILEPATH=/Applications/Xcode9.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
> 
> //Flags used by the CXX compiler during all build types.
> CMAKE_CXX_FLAGS:STRING=
> 
> //Flags used by the CXX compiler during DEBUG builds.
> CMAKE_CXX_FLAGS_DEBUG:STRING=-g
> 
> //Flags used by the CXX compiler during MINSIZEREL builds.
> CMAKE_CXX_FLAGS_MINSIZEREL:STRING=-Os -DNDEBUG
> 
> //Flags used by the CXX compiler during RELEASE builds.
> CMAKE_CXX_FLAGS_RELEASE:STRING=-O3 -DNDEBUG
> 
> //Flags used by the CXX compiler during RELWITHDEBINFO builds.
> CMAKE_CXX_FLAGS_RELWITHDEBINFO:STRING=-O2 -g -DNDEBUG
> 
> //C compiler
> CMAKE_C_COMPILER:FILEPATH=/Applications/Xcode9.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
> 
> //Flags used by the C compiler during all build types.
> CMAKE_C_FLAGS:STRING=
> 
> //Flags used by the C compiler during DEBUG builds.
> CMAKE_C_FLAGS_DEBUG:STRING=-g
> 
> //Flags used by the C compiler during MINSIZEREL builds.
> CMAKE_C_FLAGS_MINSIZEREL:STRING=-Os -DNDEBUG
> 
> //Flags used by the C compiler during RELEASE builds.
> CMAKE_C_FLAGS_RELEASE:STRING=-O3 -DNDEBUG
> 
> //Flags used by the C compiler during RELWITHDEBINFO builds.
> CMAKE_C_FLAGS_RELWITHDEBINFO:STRING=-O2 -g -DNDEBUG
> 
> //Executable file format
> CMAKE_EXECUTABLE_FORMAT:STRING=MACHO
> 
> //Flags used by the linker during all build types.
> CMAKE_EXE_LINKER_FLAGS:STRING=
> 
> //Flags used by the linker during DEBUG builds.
> CMAKE_EXE_LINKER_FLAGS_DEBUG:STRING=
> 
> //Flags used by the linker during MINSIZEREL builds.
> CMAKE_EXE_LINKER_FLAGS_MINSIZEREL:STRING=
> 
> //Flags used by the linker during RELEASE builds.
> CMAKE_EXE_LINKER_FLAGS_RELEASE:STRING=
> 
> //Flags used by the linker during RELWITHDEBINFO builds.
> CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO:STRING=
> 
> //Enable/Disable output of compile commands during generation.
> CMAKE_EXPORT_COMPILE_COMMANDS:BOOL=OFF
> 
> //Path to a program.
> CMAKE_INSTALL_NAME_TOOL:FILEPATH=/usr/bin/install_name_tool
> 
> //Install path prefix, prepended onto install directories.
> CMAKE_INSTALL_PREFIX:PATH=/usr/local
> 
> //Path to a program.
> CMAKE_LINKER:FILEPATH=/Applications/Xcode9.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld
> 
> //Path to a program.
> CMAKE_MAKE_PROGRAM:FILEPATH=/usr/bin/make
> 
> //Flags used by the linker during the creation of modules during
> // all build types.
> CMAKE_MODULE_LINKER_FLAGS:STRING=
> 
> //Flags used by the linker during the creation of modules during
> // DEBUG builds.
> CMAKE_MODULE_LINKER_FLAGS_DEBUG:STRING=
> 
> //Flags used by the linker during the creation of modules during
> // MINSIZEREL builds.
> CMAKE_MODULE_LINKER_FLAGS_MINSIZEREL:STRING=
> 
> //Flags used by the linker during the creation of modules during
> // RELEASE builds.
> CMAKE_MODULE_LINKER_FLAGS_RELEASE:STRING=
> 
> //Flags used by the linker during the creation of modules during
> // RELWITHDEBINFO builds.
> CMAKE_MODULE_LINKER_FLAGS_RELWITHDEBINFO:STRING=
> 
> //Path to a program.
> CMAKE_NM:FILEPATH=/Applications/Xcode9.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/nm
> 
> //Path to a program.
> CMAKE_OBJCOPY:FILEPATH=CMAKE_OBJCOPY-NOTFOUND
> 
> //Path to a program.
> CMAKE_OBJDUMP:FILEPATH=/Applications/Xcode9.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/objdump
> 
> //Build architectures for OSX
> CMAKE_OSX_ARCHITECTURES:STRING=
> 
> //Minimum OS X version to target for deployment (at runtime); newer
> // APIs weak linked. Set to empty string for default value.
> CMAKE_OSX_DEPLOYMENT_TARGET:STRING=
> 
> //The product will be built against the headers and libraries located
> // inside the indicated SDK.
> CMAKE_OSX_SYSROOT:STRING=
> 
> //Value Computed by CMake
> CMAKE_PROJECT_DESCRIPTION:STATIC=
> 
> //Value Computed by CMake
> CMAKE_PROJECT_HOMEPAGE_URL:STATIC=
> 
> //Value Computed by CMake
> CMAKE_PROJECT_NAME:STATIC=Samples
> 
> //Path to a program.
> CMAKE_RANLIB:FILEPATH=/Applications/Xcode9.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib
> 
> //Flags used by the linker during the creation of shared libraries
> // during all build types.
> CMAKE_SHARED_LINKER_FLAGS:STRING=
> 
> //Flags used by the linker during the creation of shared libraries
> // during DEBUG builds.
> CMAKE_SHARED_LINKER_FLAGS_DEBUG:STRING=
> 
> //Flags used by the linker during the creation of shared libraries
> // during MINSIZEREL builds.
> CMAKE_SHARED_LINKER_FLAGS_MINSIZEREL:STRING=
> 
> //Flags used by the linker during the creation of shared libraries
> // during RELEASE builds.
> CMAKE_SHARED_LINKER_FLAGS_RELEASE:STRING=
> 
> //Flags used by the linker during the creation of shared libraries
> // during RELWITHDEBINFO builds.
> CMAKE_SHARED_LINKER_FLAGS_RELWITHDEBINFO:STRING=
> 
> //If set, runtime paths are not added when installing shared libraries,
> // but are added when building.
> CMAKE_SKIP_INSTALL_RPATH:BOOL=NO
> 
> //If set, runtime paths are not added when using shared libraries.
> CMAKE_SKIP_RPATH:BOOL=NO
> 
> //Flags used by the linker during the creation of static libraries
> // during all build types.
> CMAKE_STATIC_LINKER_FLAGS:STRING=
> 
> //Flags used by the linker during the creation of static libraries
> // during DEBUG builds.
> CMAKE_STATIC_LINKER_FLAGS_DEBUG:STRING=
> 
> //Flags used by the linker during the creation of static libraries
> // during MINSIZEREL builds.
> CMAKE_STATIC_LINKER_FLAGS_MINSIZEREL:STRING=
> 
> //Flags used by the linker during the creation of static libraries
> // during RELEASE builds.
> CMAKE_STATIC_LINKER_FLAGS_RELEASE:STRING=
> 
> //Flags used by the linker during the creation of static libraries
> // during RELWITHDEBINFO builds.
> CMAKE_STATIC_LINKER_FLAGS_RELWITHDEBINFO:STRING=
> 
> //Path to a program.
> CMAKE_STRIP:FILEPATH=/Applications/Xcode9.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/strip
> 
> //If this value is on, makefiles will be generated without the
> // .SILENT directive, and all commands will be echoed to the console
> // during the make.  This is useful for debugging only. With Visual
> // Studio IDE projects all commands are done without /nologo.
> CMAKE_VERBOSE_MAKEFILE:BOOL=FALSE
> 
> //Value Computed by CMake
> Samples_BINARY_DIR:STATIC=/Users/manumolina/Documents/openFrameworks/addons/ofxultralight/libs/ultralight/build/samples
> 
> //Value Computed by CMake
> Samples_SOURCE_DIR:STATIC=/Users/manumolina/Documents/openFrameworks/addons/ofxultralight/libs/ultralight/samples
> 
> 
> ########################
> # INTERNAL cache entries
> ########################
> 
> //ADVANCED property for variable: CMAKE_AR
> CMAKE_AR-ADVANCED:INTERNAL=1
> //This is the directory where this CMakeCache.txt was created
> CMAKE_CACHEFILE_DIR:INTERNAL=/Users/manumolina/Documents/openFrameworks/addons/ofxultralight/libs/ultralight/build
> //Major version of cmake used to create the current loaded cache
> CMAKE_CACHE_MAJOR_VERSION:INTERNAL=3
> //Minor version of cmake used to create the current loaded cache
> CMAKE_CACHE_MINOR_VERSION:INTERNAL=14
> //Patch version of cmake used to create the current loaded cache
> CMAKE_CACHE_PATCH_VERSION:INTERNAL=0
> //ADVANCED property for variable: CMAKE_COLOR_MAKEFILE
> CMAKE_COLOR_MAKEFILE-ADVANCED:INTERNAL=1
> //Path to CMake executable.
> CMAKE_COMMAND:INTERNAL=/usr/local/Cellar/cmake/3.14.0/bin/cmake
> //Path to cpack program executable.
> CMAKE_CPACK_COMMAND:INTERNAL=/usr/local/Cellar/cmake/3.14.0/bin/cpack
> //Path to ctest program executable.
> CMAKE_CTEST_COMMAND:INTERNAL=/usr/local/Cellar/cmake/3.14.0/bin/ctest
> //ADVANCED property for variable: CMAKE_CXX_COMPILER
> CMAKE_CXX_COMPILER-ADVANCED:INTERNAL=1
> //ADVANCED property for variable: CMAKE_CXX_FLAGS
> CMAKE_CXX_FLAGS-ADVANCED:INTERNAL=1
> //ADVANCED property for variable: CMAKE_CXX_FLAGS_DEBUG
> CMAKE_CXX_FLAGS_DEBUG-ADVANCED:INTERNAL=1
> //ADVANCED property for variable: CMAKE_CXX_FLAGS_MINSIZEREL
> CMAKE_CXX_FLAGS_MINSIZEREL-ADVANCED:INTERNAL=1
> //ADVANCED property for variable: CMAKE_CXX_FLAGS_RELEASE
> CMAKE_CXX_FLAGS_RELEASE-ADVANCED:INTERNAL=1
> //ADVANCED property for variable: CMAKE_CXX_FLAGS_RELWITHDEBINFO
> CMAKE_CXX_FLAGS_RELWITHDEBINFO-ADVANCED:INTERNAL=1
> //ADVANCED property for variable: CMAKE_C_COMPILER
> CMAKE_C_COMPILER-ADVANCED:INTERNAL=1
> //ADVANCED property for variable: CMAKE_C_FLAGS
> CMAKE_C_FLAGS-ADVANCED:INTERNAL=1
> //ADVANCED property for variable: CMAKE_C_FLAGS_DEBUG
> CMAKE_C_FLAGS_DEBUG-ADVANCED:INTERNAL=1
> //ADVANCED property for variable: CMAKE_C_FLAGS_MINSIZEREL
> CMAKE_C_FLAGS_MINSIZEREL-ADVANCED:INTERNAL=1
> //ADVANCED property for variable: CMAKE_C_FLAGS_RELEASE
> CMAKE_C_FLAGS_RELEASE-ADVANCED:INTERNAL=1
> //ADVANCED property for variable: CMAKE_C_FLAGS_RELWITHDEBINFO
> CMAKE_C_FLAGS_RELWITHDEBINFO-ADVANCED:INTERNAL=1
> //Path to cache edit program executable.
> CMAKE_EDIT_COMMAND:INTERNAL=/usr/local/Cellar/cmake/3.14.0/bin/ccmake
> //ADVANCED property for variable: CMAKE_EXE_LINKER_FLAGS
> CMAKE_EXE_LINKER_FLAGS-ADVANCED:INTERNAL=1
> //ADVANCED property for variable: CMAKE_EXE_LINKER_FLAGS_DEBUG
> CMAKE_EXE_LINKER_FLAGS_DEBUG-ADVANCED:INTERNAL=1
> //ADVANCED property for variable: CMAKE_EXE_LINKER_FLAGS_MINSIZEREL
> CMAKE_EXE_LINKER_FLAGS_MINSIZEREL-ADVANCED:INTERNAL=1
> //ADVANCED property for variable: CMAKE_EXE_LINKER_FLAGS_RELEASE
> CMAKE_EXE_LINKER_FLAGS_RELEASE-ADVANCED:INTERNAL=1
> //ADVANCED property for variable: CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO
> CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO-ADVANCED:INTERNAL=1
> //ADVANCED property for variable: CMAKE_EXPORT_COMPILE_COMMANDS
> CMAKE_EXPORT_COMPILE_COMMANDS-ADVANCED:INTERNAL=1
> //Name of external makefile project generator.
> CMAKE_EXTRA_GENERATOR:INTERNAL=
> //Name of generator.
> CMAKE_GENERATOR:INTERNAL=Unix Makefiles
> //Generator instance identifier.
> CMAKE_GENERATOR_INSTANCE:INTERNAL=
> //Name of generator platform.
> CMAKE_GENERATOR_PLATFORM:INTERNAL=
> //Name of generator toolset.
> CMAKE_GENERATOR_TOOLSET:INTERNAL=
> //Source directory with the top level CMakeLists.txt file for this
> // project
> CMAKE_HOME_DIRECTORY:INTERNAL=/Users/manumolina/Documents/openFrameworks/addons/ofxultralight/libs/ultralight
> //ADVANCED property for variable: CMAKE_INSTALL_NAME_TOOL
> CMAKE_INSTALL_NAME_TOOL-ADVANCED:INTERNAL=1
> //ADVANCED property for variable: CMAKE_LINKER
> CMAKE_LINKER-ADVANCED:INTERNAL=1
> //ADVANCED property for variable: CMAKE_MAKE_PROGRAM
> CMAKE_MAKE_PROGRAM-ADVANCED:INTERNAL=1
> //ADVANCED property for variable: CMAKE_MODULE_LINKER_FLAGS
> CMAKE_MODULE_LINKER_FLAGS-ADVANCED:INTERNAL=1
> //ADVANCED property for variable: CMAKE_MODULE_LINKER_FLAGS_DEBUG
> CMAKE_MODULE_LINKER_FLAGS_DEBUG-ADVANCED:INTERNAL=1
> //ADVANCED property for variable: CMAKE_MODULE_LINKER_FLAGS_MINSIZEREL
> CMAKE_MODULE_LINKER_FLAGS_MINSIZEREL-ADVANCED:INTERNAL=1
> //ADVANCED property for variable: CMAKE_MODULE_LINKER_FLAGS_RELEASE
> CMAKE_MODULE_LINKER_FLAGS_RELEASE-ADVANCED:INTERNAL=1
> //ADVANCED property for variable: CMAKE_MODULE_LINKER_FLAGS_RELWITHDEBINFO
> CMAKE_MODULE_LINKER_FLAGS_RELWITHDEBINFO-ADVANCED:INTERNAL=1
> //ADVANCED property for variable: CMAKE_NM
> CMAKE_NM-ADVANCED:INTERNAL=1
> //number of local generators
> CMAKE_NUMBER_OF_MAKEFILES:INTERNAL=7
> //ADVANCED property for variable: CMAKE_OBJCOPY
> CMAKE_OBJCOPY-ADVANCED:INTERNAL=1
> //ADVANCED property for variable: CMAKE_OBJDUMP
> CMAKE_OBJDUMP-ADVANCED:INTERNAL=1
> //Platform information initialized
> CMAKE_PLATFORM_INFO_INITIALIZED:INTERNAL=1
> //ADVANCED property for variable: CMAKE_RANLIB
> CMAKE_RANLIB-ADVANCED:INTERNAL=1
> //Path to CMake installation.
> CMAKE_ROOT:INTERNAL=/usr/local/Cellar/cmake/3.14.0/share/cmake
> //ADVANCED property for variable: CMAKE_SHARED_LINKER_FLAGS
> CMAKE_SHARED_LINKER_FLAGS-ADVANCED:INTERNAL=1
> //ADVANCED property for variable: CMAKE_SHARED_LINKER_FLAGS_DEBUG
> CMAKE_SHARED_LINKER_FLAGS_DEBUG-ADVANCED:INTERNAL=1
> //ADVANCED property for variable: CMAKE_SHARED_LINKER_FLAGS_MINSIZEREL
> CMAKE_SHARED_LINKER_FLAGS_MINSIZEREL-ADVANCED:INTERNAL=1
> //ADVANCED property for variable: CMAKE_SHARED_LINKER_FLAGS_RELEASE
> CMAKE_SHARED_LINKER_FLAGS_RELEASE-ADVANCED:INTERNAL=1
> //ADVANCED property for variable: CMAKE_SHARED_LINKER_FLAGS_RELWITHDEBINFO
> CMAKE_SHARED_LINKER_FLAGS_RELWITHDEBINFO-ADVANCED:INTERNAL=1
> //ADVANCED property for variable: CMAKE_SKIP_INSTALL_RPATH
> CMAKE_SKIP_INSTALL_RPATH-ADVANCED:INTERNAL=1
> //ADVANCED property for variable: CMAKE_SKIP_RPATH
> CMAKE_SKIP_RPATH-ADVANCED:INTERNAL=1
> //ADVANCED property for variable: CMAKE_STATIC_LINKER_FLAGS
> CMAKE_STATIC_LINKER_FLAGS-ADVANCED:INTERNAL=1
> //ADVANCED property for variable: CMAKE_STATIC_LINKER_FLAGS_DEBUG
> CMAKE_STATIC_LINKER_FLAGS_DEBUG-ADVANCED:INTERNAL=1
> //ADVANCED property for variable: CMAKE_STATIC_LINKER_FLAGS_MINSIZEREL
> CMAKE_STATIC_LINKER_FLAGS_MINSIZEREL-ADVANCED:INTERNAL=1
> //ADVANCED property for variable: CMAKE_STATIC_LINKER_FLAGS_RELEASE
> CMAKE_STATIC_LINKER_FLAGS_RELEASE-ADVANCED:INTERNAL=1
> //ADVANCED property for variable: CMAKE_STATIC_LINKER_FLAGS_RELWITHDEBINFO
> CMAKE_STATIC_LINKER_FLAGS_RELWITHDEBINFO-ADVANCED:INTERNAL=1
> //ADVANCED property for variable: CMAKE_STRIP
> CMAKE_STRIP-ADVANCED:INTERNAL=1
> //uname command
> CMAKE_UNAME:INTERNAL=/usr/bin/uname
> //ADVANCED property for variable: CMAKE_VERBOSE_MAKEFILE
> CMAKE_VERBOSE_MAKEFILE-ADVANCED:INTERNAL=1
> 
>

**Comment by IngwiePhoenix** [comment]
The error message says that CMake has previously generated Unix Makefiles in this very folder. You can delete and re-create that folder... or just use Make - which is perfectly fine too :)

**Comment by moebiussurfing** [comment]
thanks. sorry again, it works both ways. but when I click any compiled .app it flashes but do not opens..
/Documents/JS/Ultralight/build/samples/Browser/Browser.app
/Documents/JS/Ultralight/build/samples/Tutorial 2 - Basic App/Tutorial2.app

in system preferences i have enabled all also not identified devs..

I downloaded again your repo from github, like some weeks ago.
