### ISSUE TITLE
Browser: Google search results don't look good...at all.

### ISSUE THREAD

**Issue by IngwiePhoenix** [ultralight-ux/Ultralight#87]
**Summarize the Issue**
After opening Google and entering a search query (which already caused a couple of fragments to be displayed which look like the page was partially being highlighted), the search results shown after hitting the search button look completely scrambled.

**Steps to Reproduce**
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/2893716/54644700-3ff5c080-4a9a-11e9-858b-56df46a06c9c.png">

**Platform Info:**
 - OS:
```
ProductName:	Mac OS X
ProductVersion:	10.14.3
BuildVersion:	18D109
```
 - SDK Version [e.g. 0.8, 0.9]
```
$ git rev-parse HEAD
9ea26b3bc2566662a4a01c6220d3fabfdc0a1dbf
```

**In addition...**
```
$ ./samples/Browser/Browser.app/Contents/MacOS/Browser
TODO: Image::loadPlatformResource missingImage
```

**Comment by IngwiePhoenix** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/2893716/54644784-8a773d00-4a9a-11e9-9988-5b51b078faec.png">

This also just appeared.

**Comment by IngwiePhoenix** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/2893716/54645035-243eea00-4a9b-11e9-979f-c843a97c8a08.png">

One more. Are those for debugging?

**Comment by KenanSulayman** [comment]
Can't replicate the issue.

<img width="963" alt="CleanShot 2019-03-19 at 23 03 53@2x" src="https://user-images.githubusercontent.com/280212/54645106-551f1f00-4a9b-11e9-9471-74bfb3b9a7e4.png">

macOS 10.14.4 Beta (18E220a), also on 9ea26b3bc2566662a4a01c6220d3fabfdc0a1dbf.

Are you using an eGPU? What GPU are you using specifically?

**Comment by adamjs** [comment]
Finally! I've been looking for someone who can replicate this issue-- it was reported a while ago but I didn't have hardware details to reproduce. What's your machine details?

**Comment by IngwiePhoenix** [comment]
```
$ system_profiler SPDisplaysDataType
Graphics/Displays:

    Intel Iris Pro:

      Chipset Model: Intel Iris Pro
      Type: GPU
      Bus: Built-In
      VRAM (Dynamic, Max): 1536 MB
      Vendor: Intel
      Device ID: 0x0d26
      Revision ID: 0x0008
      Automatic Graphics Switching: Supported
      gMux Version: 4.0.8 [3.2.8]
      Metal: Supported, feature set macOS GPUFamily1 v4

    NVIDIA GeForce GT 750M:

      Chipset Model: NVIDIA GeForce GT 750M
      Type: GPU
      Bus: PCIe
      PCIe Lane Width: x8
      VRAM (Dynamic, Max): 2048 MB
      Vendor: NVIDIA (0x10de)
      Device ID: 0x0fe9
      Revision ID: 0x00a2
      ROM Revision: 3776
      Automatic Graphics Switching: Supported
      gMux Version: 4.0.8 [3.2.8]
      Metal: Supported, feature set macOS GPUFamily1 v4
      Displays:
        Color LCD:
          Display Type: Built-In Retina LCD
          Resolution: 2880 x 1800 Retina
          Framebuffer Depth: 24-Bit Color (ARGB8888)
          Main Display: Yes
          Mirror: Off
          Online: Yes
          Rotation: Supported
          Automatically Adjust Brightness: No
```

This :)

**Comment by adamjs** [comment]
Awesome! Do you also happen to have the MacBook model info? I'll try to get the same one to test.

**Comment by KenanSulayman** [comment]
I bet it's a late 2013 15" Macbook Pro

**Comment by IngwiePhoenix** [comment]
Almost! Mid-2014. :) Let's see...

```
$ system_profiler SPHardwareDataType
Hardware:

    Hardware Overview:

      Model Name: MacBook Pro
      Model Identifier: MacBookPro11,3
      Processor Name: Intel Core i7
      Processor Speed: 2,8 GHz
      Number of Processors: 1
      Total Number of Cores: 4
      L2 Cache (per Core): 256 KB
      L3 Cache: 6 MB
      Memory: 16 GB
      Boot ROM Version: 149.0.0.0.0
      SMC Version (system): 2.19f12
      Serial Number (system): C02N84D1G3QP
      Hardware UUID: 88841E38-C6D0-54F1-983A-3D18A219FD44
```

I think this should explain everything.

**Comment by adamjs** [comment]
Thanks! Should have a matching MBP coming next week, will debug and fix.
