### ISSUE TITLE
Noticeable mouse lag when loading a page with many elements 

### ISSUE THREAD

**Issue by tqphan** [ultralight-ux/Ultralight#91]
Hello,
I'm making an on-screen keyboard and considering ultralight. I use the Tutorial 3 - Resizable App
with just a single modification: 
`
    overlay_->view()->LoadURL("http://bulletshoot.000webhostapp.com/test.html");
`
There is a huge noticeable mouse lag when hovering over keys.
Am I doing something wrong?

**Comment by maierfelix** [comment]
Probably related to https://github.com/ultralight-ux/ultralight/issues/46
This is caused by a missing optimization, right now each style-tree modification triggers a full site repaint

**Comment by adamjs** [comment]
Sorry about that, this issue was caused by a line of debug code I accidentally left in that was forcing repaints on every mouse event. I'll put out some updated binaries soon with a fix.
