### ISSUE TITLE
Browser demo craches

### ISSUE THREAD

**Issue by ImOnALampshade** [ultralight-ux/ultralight#96]
**Summarize the Issue**
Running browser demo after downloading latest SDK from ultralight website, crashes on calling `updateLoading` in `UI::SetLoading` when starting the demo.

Exception reads: `Exception thrown at 0x00000238E391BDB8 in Browser.exe: 0xC0000005: Access violation executing location 0x00000238E391BDB8.`

**Steps to Reproduce**
Download & unzip
```
md build
cd build
cmake .. -G "Visual Studio 15 2017 Win64"
```
Open ultralight.sln and run the browser project

**Platform Info:**
 - OS: Windows 10
 - SDK Version 1.0

**Comment by adamjs** [comment]
This should be fixed in latest trunk, (was caused by passing std::vector across library boundaries— application and shared libraries have separate heaps so they shouldn’t be crossed).

Can you clone latest revision and see?

**Comment by ImOnALampshade** [comment]
Sorry, it took a very long time to clone on my home internet. Cloning off git fixed the issue.

Should I open a separate issue about storing dll files in git, or is that something that's planned to stick around for a while?

**Comment by adamjs** [comment]
It's planned :), just opened a new issue for it: https://github.com/ultralight-ux/ultralight/issues/98
